My Project: EVENT_FABRIC_RW_API.h File Reference
EVENT_FABRIC_RW_API.h File Reference
#include "EVENT_FABRIC_REGS.h"
Functions
static void EVENT_FABRIC_PWR_EN_WRITE (EVENT_FABRIC_REGS_s *registers, uint32_t pwr_en, uint32_t pwr_en_key)
static void EVENT_FABRIC_RST_CTRL_WRITE (EVENT_FABRIC_REGS_s *registers, uint32_t rst, uint32_t rst_sts_clr, uint32_t rst_key)
static void EVENT_FABRIC_CLK_CTRL_WRITE (EVENT_FABRIC_REGS_s *registers, uint32_t clk_en)
static void EVENT_FABRIC_GEN_PUB_N_WRITE (EVENT_FABRIC_REGS_s *registers, uint32_t index, uint32_t gen_pub_chan_id)
static void EVENT_FABRIC_GEN_SUB_N_WRITE (EVENT_FABRIC_REGS_s *registers, uint32_t index, uint32_t gen_sub_chan_id)
static void EVENT_FABRIC_DMA_PUB_N_WRITE (EVENT_FABRIC_REGS_s *registers, uint32_t index, uint32_t dma_pub_event_id)
Function Documentation
EVENT_FABRIC_PWR_EN_WRITE()
void EVENT_FABRIC_PWR_EN_WRITE (EVENT_FABRIC_REGS_s * registers, uint32_t pwr_en, uint32_t pwr_en_key) inline static
References EVENT_FABRIC_PWR_EN_PWR_EN_KEY_MASK, EVENT_FABRIC_PWR_EN_PWR_EN_KEY_OFS, EVENT_FABRIC_PWR_EN_PWR_EN_MASK, EVENT_FABRIC_PWR_EN_PWR_EN_OFS, EVENT_FABRIC_PWR_EN_u::packed_w, and EVENT_FABRIC_REGS_s::PWR_EN.
EVENT_FABRIC_RST_CTRL_WRITE()
void EVENT_FABRIC_RST_CTRL_WRITE (EVENT_FABRIC_REGS_s * registers, uint32_t rst, uint32_t rst_sts_clr, uint32_t rst_key) inline static
References EVENT_FABRIC_RST_CTRL_RST_KEY_MASK, EVENT_FABRIC_RST_CTRL_RST_KEY_OFS, EVENT_FABRIC_RST_CTRL_RST_MASK, EVENT_FABRIC_RST_CTRL_RST_OFS, EVENT_FABRIC_RST_CTRL_RST_STS_CLR_MASK, EVENT_FABRIC_RST_CTRL_RST_STS_CLR_OFS, EVENT_FABRIC_RST_CTRL_u::packed_w, and EVENT_FABRIC_REGS_s::RST_CTRL.
EVENT_FABRIC_CLK_CTRL_WRITE()
void EVENT_FABRIC_CLK_CTRL_WRITE (EVENT_FABRIC_REGS_s * registers, uint32_t clk_en) inline static
References EVENT_FABRIC_REGS_s::CLK_CTRL, EVENT_FABRIC_CLK_CTRL_CLK_EN_MASK, EVENT_FABRIC_CLK_CTRL_CLK_EN_OFS, and EVENT_FABRIC_CLK_CTRL_u::packed_w.
EVENT_FABRIC_GEN_PUB_N_WRITE()
void EVENT_FABRIC_GEN_PUB_N_WRITE (EVENT_FABRIC_REGS_s * registers, uint32_t index, uint32_t gen_pub_chan_id) inline static
References EVENT_FABRIC_GEN_PUB_GEN_PUB_CHAN_ID_MASK, EVENT_FABRIC_GEN_PUB_GEN_PUB_CHAN_ID_OFS, EVENT_FABRIC_REGS_s::GEN_PUB, and EVENT_FABRIC_GEN_PUB_u::packed_w.
Referenced by event_fabric_pub_to_sub_channel_cfg().
EVENT_FABRIC_GEN_SUB_N_WRITE()
void EVENT_FABRIC_GEN_SUB_N_WRITE (EVENT_FABRIC_REGS_s * registers, uint32_t index, uint32_t gen_sub_chan_id) inline static
References EVENT_FABRIC_GEN_SUB_GEN_SUB_CHAN_ID_MASK, EVENT_FABRIC_GEN_SUB_GEN_SUB_CHAN_ID_OFS, EVENT_FABRIC_REGS_s::GEN_SUB, and EVENT_FABRIC_GEN_SUB_u::packed_w.
Referenced by event_fabric_pub_to_sub_channel_cfg().
EVENT_FABRIC_DMA_PUB_N_WRITE()
void EVENT_FABRIC_DMA_PUB_N_WRITE (EVENT_FABRIC_REGS_s * registers, uint32_t index, uint32_t dma_pub_event_id) inline static
References EVENT_FABRIC_REGS_s::DMA_PUB, EVENT_FABRIC_DMA_PUB_DMA_PUB_EVENT_ID_MASK, EVENT_FABRIC_DMA_PUB_DMA_PUB_EVENT_ID_OFS, and EVENT_FABRIC_DMA_PUB_u::packed_w.
Referenced by event_fabric_pub_to_dma_channel_cfg().