My Project: I2C_RW_API.h File Reference
I2C_RW_API.h File Reference
#include "I2C_REGS.h"
Functions
static void I2C_PWR_EN_WRITE (I2C_REGS_s *registers, uint32_t pwr_en, uint32_t pwr_en_key)
static void I2C_RST_CTRL_WRITE (I2C_REGS_s *registers, uint32_t rst, uint32_t rst_sts_clr, uint32_t rst_key)
static void I2C_CLK_CTRL_WRITE (I2C_REGS_s *registers, uint32_t en_async_clk_req, uint32_t clksel, uint32_t clkdiv, uint32_t hold_cnt, uint32_t setup_cnt)
static void I2C_DBG_CTRL_WRITE (I2C_REGS_s *registers, uint32_t run_on_halt, uint32_t soft_stop)
static void I2C_MASTER_SCL_GEN_WRITE (I2C_REGS_s *registers, uint32_t mst_scl_cnt_high_val, uint32_t mst_scl_cnt_low_val)
static void I2C_MASTER_TIMING_CONSTRAINT_WRITE (I2C_REGS_s *registers, uint32_t mst_scl_start_cnt, uint32_t mst_sda_stop_cnt, uint32_t mst_stop_start_buffer_cnt, uint32_t mst_restart_setup_cnt)
static void I2C_MASTER_CLKSTRETCH_CNT_WRITE (I2C_REGS_s *registers, uint32_t mst_max_clkstretch_cnt)
static void I2C_SLAVE_CLKSTRETCH_CNT_WRITE (I2C_REGS_s *registers, uint32_t slv_max_clkstretch_cnt)
static void I2C_SMBUS_TIMEOUT_CNT_WRITE (I2C_REGS_s *registers, uint32_t smbus_timeout_cnt)
static void I2C_INTR_EVENT_CLEAR (I2C_REGS_s *registers, uint32_t intr_idx)
static void I2C_INTR_EVENT_EN (I2C_REGS_s *registers, uint32_t intr_idx)
static void I2C_INTR_EVENT_DIS (I2C_REGS_s *registers, uint32_t intr_idx)
static void I2C_INTR_EVENT_NMI_EN (I2C_REGS_s *registers, uint32_t intr_idx)
static void I2C_INTR_EVENT_NMI_DIS (I2C_REGS_s *registers, uint32_t intr_idx)
static void I2C_GENERIC_RX_DMA_EVENT_EN_ (I2C_REGS_s *registers, uint32_t intr_idx)
static void I2C_GENERIC_RX_DMA_EVENT_DIS_ (I2C_REGS_s *registers, uint32_t intr_idx)
static void I2C_GENERIC_TX_DMA_EVENT_EN_ (I2C_REGS_s *registers, uint32_t intr_idx)
static void I2C_GENERIC_TX_DMA_EVENT_DIS_ (I2C_REGS_s *registers, uint32_t intr_idx)
static void I2C_INTR_SW_SET_0 (I2C_REGS_s *registers, uint32_t intr_idx)
static void I2C_INTR_SW_SET_1 (I2C_REGS_s *registers, uint32_t intr_idx)
static void I2C_SPARE_CTRL_WRITE (I2C_REGS_s *registers, uint32_t cfg0, uint32_t cfg1)
static void I2C_GLITCH_FILTER_CFG_WRITE (I2C_REGS_s *registers, uint32_t gf_width)
static void I2C_SLAVE_CTRL_WRITE (I2C_REGS_s *registers, uint32_t slv_addr_mode, uint32_t slv_low_pwr_wakeup_en, uint32_t slv_def_dev_addr_en, uint32_t slv_alres_addr_en, uint32_t slv_def_host_addr_en, uint32_t slv_txtrig_at_txmode, uint32_t slv_clkstretch_en, uint32_t slv_gencall_en, uint32_t slv_enable, uint32_t slv_addr2_en, uint32_t slv_addr2_mask, uint32_t slv_txwait_stale_fifo, uint32_t slv_txempty_intr_on_tx_req)
static void I2C_SLAVE_ADDR_WRITE (I2C_REGS_s *registers, uint32_t slv_addr1, uint32_t slv_addr2)
static void I2C_SLAVE_ACK_CFG_WRITE (I2C_REGS_s *registers, uint32_t slv_auto_ack_en, uint32_t slv_addr_auto_ack_en)
static void I2C_SLAVE_BYTE_ACK_WRITE (I2C_REGS_s *registers, uint32_t slv_ackval)
static void I2C_FIFO_CTRL_WRITE (I2C_REGS_s *registers, uint32_t rxfifo_en, uint32_t txfifo_en, uint32_t rxfifo_flush, uint32_t txfifo_flush)
static void I2C_TXDATA_N_WRITE (I2C_REGS_s *registers, uint32_t index, uint32_t txdata)
static void I2C_PEC_CTRL_WRITE (I2C_REGS_s *registers, uint32_t pec_en)
static void I2C_MASTER_CFG_WRITE (I2C_REGS_s *registers, uint32_t mst_enable, uint32_t mst_clkstretch_en, uint32_t lpbk_mode, uint32_t mst_auto_ack_en, uint32_t mst_addr_mode, uint32_t mst_slv_addr_cfg)
static void I2C_MASTER_CTRL_WRITE (I2C_REGS_s *registers, uint32_t mst_cmd_vld, uint32_t mst_burst_len, uint32_t mst_start, uint32_t mst_dir, uint32_t mst_stop, uint32_t mst_rd_on_txempty)
static void I2C_MASTER_ACK_VAL_WRITE (I2C_REGS_s *registers, uint32_t mst_ackval)
Function Documentation
I2C_PWR_EN_WRITE()
void I2C_PWR_EN_WRITE (I2C_REGS_s * registers, uint32_t pwr_en, uint32_t pwr_en_key) inline static
References I2C_PWR_EN_PWR_EN_KEY_MASK, I2C_PWR_EN_PWR_EN_KEY_OFS, I2C_PWR_EN_PWR_EN_MASK, I2C_PWR_EN_PWR_EN_OFS, I2C_PWR_EN_u::packed_w, and I2C_REGS_s::PWR_EN.
I2C_RST_CTRL_WRITE()
void I2C_RST_CTRL_WRITE (I2C_REGS_s * registers, uint32_t rst, uint32_t rst_sts_clr, uint32_t rst_key) inline static
References I2C_RST_CTRL_RST_KEY_MASK, I2C_RST_CTRL_RST_KEY_OFS, I2C_RST_CTRL_RST_MASK, I2C_RST_CTRL_RST_OFS, I2C_RST_CTRL_RST_STS_CLR_MASK, I2C_RST_CTRL_RST_STS_CLR_OFS, I2C_RST_CTRL_u::packed_w, and I2C_REGS_s::RST_CTRL.
I2C_CLK_CTRL_WRITE()
void I2C_CLK_CTRL_WRITE (I2C_REGS_s * registers, uint32_t en_async_clk_req, uint32_t clksel, uint32_t clkdiv, uint32_t hold_cnt, uint32_t setup_cnt) inline static
References I2C_REGS_s::CLK_CTRL, I2C_CLK_CTRL_CLKDIV_MASK, I2C_CLK_CTRL_CLKDIV_OFS, I2C_CLK_CTRL_CLKSEL_MASK, I2C_CLK_CTRL_CLKSEL_OFS, I2C_CLK_CTRL_EN_ASYNC_CLK_REQ_MASK, I2C_CLK_CTRL_EN_ASYNC_CLK_REQ_OFS, I2C_CLK_CTRL_HOLD_CNT_MASK, I2C_CLK_CTRL_HOLD_CNT_OFS, I2C_CLK_CTRL_SETUP_CNT_MASK, I2C_CLK_CTRL_SETUP_CNT_OFS, and I2C_CLK_CTRL_u::packed_w.
I2C_DBG_CTRL_WRITE()
void I2C_DBG_CTRL_WRITE (I2C_REGS_s * registers, uint32_t run_on_halt, uint32_t soft_stop) inline static
References I2C_REGS_s::DBG_CTRL, I2C_DBG_CTRL_RUN_ON_HALT_MASK, I2C_DBG_CTRL_RUN_ON_HALT_OFS, I2C_DBG_CTRL_SOFT_STOP_MASK, I2C_DBG_CTRL_SOFT_STOP_OFS, and I2C_DBG_CTRL_u::packed_w.
I2C_MASTER_SCL_GEN_WRITE()
void I2C_MASTER_SCL_GEN_WRITE (I2C_REGS_s * registers, uint32_t mst_scl_cnt_high_val, uint32_t mst_scl_cnt_low_val) inline static
References I2C_MASTER_SCL_GEN_MST_SCL_CNT_HIGH_VAL_MASK, I2C_MASTER_SCL_GEN_MST_SCL_CNT_HIGH_VAL_OFS, I2C_MASTER_SCL_GEN_MST_SCL_CNT_LOW_VAL_MASK, I2C_MASTER_SCL_GEN_MST_SCL_CNT_LOW_VAL_OFS, I2C_REGS_s::MASTER_SCL_GEN, and I2C_MASTER_SCL_GEN_u::packed_w.
I2C_MASTER_TIMING_CONSTRAINT_WRITE()
void I2C_MASTER_TIMING_CONSTRAINT_WRITE (I2C_REGS_s * registers, uint32_t mst_scl_start_cnt, uint32_t mst_sda_stop_cnt, uint32_t mst_stop_start_buffer_cnt, uint32_t mst_restart_setup_cnt) inline static
References I2C_MASTER_TIMING_CONSTRAINT_MST_RESTART_SETUP_CNT_MASK, I2C_MASTER_TIMING_CONSTRAINT_MST_RESTART_SETUP_CNT_OFS, I2C_MASTER_TIMING_CONSTRAINT_MST_SCL_START_CNT_MASK, I2C_MASTER_TIMING_CONSTRAINT_MST_SCL_START_CNT_OFS, I2C_MASTER_TIMING_CONSTRAINT_MST_SDA_STOP_CNT_MASK, I2C_MASTER_TIMING_CONSTRAINT_MST_SDA_STOP_CNT_OFS, I2C_MASTER_TIMING_CONSTRAINT_MST_STOP_START_BUFFER_CNT_MASK, I2C_MASTER_TIMING_CONSTRAINT_MST_STOP_START_BUFFER_CNT_OFS, I2C_REGS_s::MASTER_TIMING_CONSTRAINT, and I2C_MASTER_TIMING_CONSTRAINT_u::packed_w.
I2C_MASTER_CLKSTRETCH_CNT_WRITE()
void I2C_MASTER_CLKSTRETCH_CNT_WRITE (I2C_REGS_s * registers, uint32_t mst_max_clkstretch_cnt) inline static
References I2C_MASTER_CLKSTRETCH_CNT_MST_MAX_CLKSTRETCH_CNT_MASK, I2C_MASTER_CLKSTRETCH_CNT_MST_MAX_CLKSTRETCH_CNT_OFS, I2C_REGS_s::MASTER_CLKSTRETCH_CNT, and I2C_MASTER_CLKSTRETCH_CNT_u::packed_w.
I2C_SLAVE_CLKSTRETCH_CNT_WRITE()
void I2C_SLAVE_CLKSTRETCH_CNT_WRITE (I2C_REGS_s * registers, uint32_t slv_max_clkstretch_cnt) inline static
References I2C_SLAVE_CLKSTRETCH_CNT_SLV_MAX_CLKSTRETCH_CNT_MASK, I2C_SLAVE_CLKSTRETCH_CNT_SLV_MAX_CLKSTRETCH_CNT_OFS, I2C_SLAVE_CLKSTRETCH_CNT_u::packed_w, and I2C_REGS_s::SLAVE_CLKSTRETCH_CNT.
I2C_SMBUS_TIMEOUT_CNT_WRITE()
void I2C_SMBUS_TIMEOUT_CNT_WRITE (I2C_REGS_s * registers, uint32_t smbus_timeout_cnt) inline static
References I2C_SMBUS_TIMEOUT_CNT_SMBUS_TIMEOUT_CNT_MASK, I2C_SMBUS_TIMEOUT_CNT_SMBUS_TIMEOUT_CNT_OFS, I2C_SMBUS_TIMEOUT_CNT_u::packed_w, and I2C_REGS_s::SMBUS_TIMEOUT_CNT.
I2C_INTR_EVENT_CLEAR()
void I2C_INTR_EVENT_CLEAR (I2C_REGS_s * registers, uint32_t intr_idx) inline static
References I2C_REGS_s::INTR_EVENT, and I2C_INTR_EVENT_u::packed_w.
Referenced by i2c_poll_for_slv_stop(), i2c_wait_for_rx_done(), i2c_wait_for_slv_start(), and i2c_wait_for_tx_done().
I2C_INTR_EVENT_EN()
void I2C_INTR_EVENT_EN (I2C_REGS_s * registers, uint32_t intr_idx) inline static
References I2C_REGS_s::INTR_EN_0, I2C_REGS_s::INTR_EN_1, I2C_INTR_EN_0_u::packed_w, and I2C_INTR_EN_1_u::packed_w.
I2C_INTR_EVENT_DIS()
void I2C_INTR_EVENT_DIS (I2C_REGS_s * registers, uint32_t intr_idx) inline static
References I2C_REGS_s::INTR_EN_0, I2C_REGS_s::INTR_EN_1, I2C_INTR_EN_0_u::packed_w, and I2C_INTR_EN_1_u::packed_w.
I2C_INTR_EVENT_NMI_EN()
void I2C_INTR_EVENT_NMI_EN (I2C_REGS_s * registers, uint32_t intr_idx) inline static
References I2C_REGS_s::INTR_NMI_EN_0, I2C_REGS_s::INTR_NMI_EN_1, I2C_INTR_NMI_EN_0_u::packed_w, and I2C_INTR_NMI_EN_1_u::packed_w.
I2C_INTR_EVENT_NMI_DIS()
void I2C_INTR_EVENT_NMI_DIS (I2C_REGS_s * registers, uint32_t intr_idx) inline static
References I2C_REGS_s::INTR_NMI_EN_0, I2C_REGS_s::INTR_NMI_EN_1, I2C_INTR_NMI_EN_0_u::packed_w, and I2C_INTR_NMI_EN_1_u::packed_w.
I2C_GENERIC_RX_DMA_EVENT_EN_()
void I2C_GENERIC_RX_DMA_EVENT_EN_ (I2C_REGS_s * registers, uint32_t intr_idx) inline static
References I2C_RX_DMA_EVENT_EN_0_u::packed_w, I2C_RX_DMA_EVENT_EN_1_u::packed_w, I2C_REGS_s::RX_DMA_EVENT_EN_0, and I2C_REGS_s::RX_DMA_EVENT_EN_1.
I2C_GENERIC_RX_DMA_EVENT_DIS_()
void I2C_GENERIC_RX_DMA_EVENT_DIS_ (I2C_REGS_s * registers, uint32_t intr_idx) inline static
References I2C_RX_DMA_EVENT_EN_0_u::packed_w, I2C_RX_DMA_EVENT_EN_1_u::packed_w, I2C_REGS_s::RX_DMA_EVENT_EN_0, and I2C_REGS_s::RX_DMA_EVENT_EN_1.
I2C_GENERIC_TX_DMA_EVENT_EN_()
void I2C_GENERIC_TX_DMA_EVENT_EN_ (I2C_REGS_s * registers, uint32_t intr_idx) inline static
References I2C_TX_DMA_EVENT_EN_0_u::packed_w, I2C_TX_DMA_EVENT_EN_1_u::packed_w, I2C_REGS_s::TX_DMA_EVENT_EN_0, and I2C_REGS_s::TX_DMA_EVENT_EN_1.
I2C_GENERIC_TX_DMA_EVENT_DIS_()
void I2C_GENERIC_TX_DMA_EVENT_DIS_ (I2C_REGS_s * registers, uint32_t intr_idx) inline static
References I2C_TX_DMA_EVENT_EN_0_u::packed_w, I2C_TX_DMA_EVENT_EN_1_u::packed_w, I2C_REGS_s::TX_DMA_EVENT_EN_0, and I2C_REGS_s::TX_DMA_EVENT_EN_1.
I2C_INTR_SW_SET_0()
void I2C_INTR_SW_SET_0 (I2C_REGS_s * registers, uint32_t intr_idx) inline static
References I2C_REGS_s::INTR_SW_SET_0, and I2C_INTR_SW_SET_0_u::packed_w.
I2C_INTR_SW_SET_1()
void I2C_INTR_SW_SET_1 (I2C_REGS_s * registers, uint32_t intr_idx) inline static
References I2C_REGS_s::INTR_SW_SET_1, and I2C_INTR_SW_SET_1_u::packed_w.
I2C_SPARE_CTRL_WRITE()
void I2C_SPARE_CTRL_WRITE (I2C_REGS_s * registers, uint32_t cfg0, uint32_t cfg1) inline static
References I2C_SPARE_CTRL_CFG0_MASK, I2C_SPARE_CTRL_CFG0_OFS, I2C_SPARE_CTRL_CFG1_MASK, I2C_SPARE_CTRL_CFG1_OFS, I2C_SPARE_CTRL_u::packed_w, and I2C_REGS_s::SPARE_CTRL.
I2C_GLITCH_FILTER_CFG_WRITE()
void I2C_GLITCH_FILTER_CFG_WRITE (I2C_REGS_s * registers, uint32_t gf_width) inline static
References I2C_REGS_s::GLITCH_FILTER_CFG, I2C_GLITCH_FILTER_CFG_GF_WIDTH_MASK, I2C_GLITCH_FILTER_CFG_GF_WIDTH_OFS, and I2C_GLITCH_FILTER_CFG_u::packed_w.
I2C_SLAVE_CTRL_WRITE()
void I2C_SLAVE_CTRL_WRITE (I2C_REGS_s * registers, uint32_t slv_addr_mode, uint32_t slv_low_pwr_wakeup_en, uint32_t slv_def_dev_addr_en, uint32_t slv_alres_addr_en, uint32_t slv_def_host_addr_en, uint32_t slv_txtrig_at_txmode, uint32_t slv_clkstretch_en, uint32_t slv_gencall_en, uint32_t slv_enable, uint32_t slv_addr2_en, uint32_t slv_addr2_mask, uint32_t slv_txwait_stale_fifo, uint32_t slv_txempty_intr_on_tx_req) inline static
References I2C_SLAVE_CTRL_SLV_ADDR2_EN_MASK, I2C_SLAVE_CTRL_SLV_ADDR2_EN_OFS, I2C_SLAVE_CTRL_SLV_ADDR2_MASK_MASK, I2C_SLAVE_CTRL_SLV_ADDR2_MASK_OFS, I2C_SLAVE_CTRL_SLV_ADDR_MODE_MASK, I2C_SLAVE_CTRL_SLV_ADDR_MODE_OFS, I2C_SLAVE_CTRL_SLV_ALRES_ADDR_EN_MASK, I2C_SLAVE_CTRL_SLV_ALRES_ADDR_EN_OFS, I2C_SLAVE_CTRL_SLV_CLKSTRETCH_EN_MASK, I2C_SLAVE_CTRL_SLV_CLKSTRETCH_EN_OFS, I2C_SLAVE_CTRL_SLV_DEF_DEV_ADDR_EN_MASK, I2C_SLAVE_CTRL_SLV_DEF_DEV_ADDR_EN_OFS, I2C_SLAVE_CTRL_SLV_DEF_HOST_ADDR_EN_MASK, I2C_SLAVE_CTRL_SLV_DEF_HOST_ADDR_EN_OFS, I2C_SLAVE_CTRL_SLV_ENABLE_MASK, I2C_SLAVE_CTRL_SLV_ENABLE_OFS, I2C_SLAVE_CTRL_SLV_GENCALL_EN_MASK, I2C_SLAVE_CTRL_SLV_GENCALL_EN_OFS, I2C_SLAVE_CTRL_SLV_LOW_PWR_WAKEUP_EN_MASK, I2C_SLAVE_CTRL_SLV_LOW_PWR_WAKEUP_EN_OFS, I2C_SLAVE_CTRL_SLV_TXEMPTY_INTR_ON_TX_REQ_MASK, I2C_SLAVE_CTRL_SLV_TXEMPTY_INTR_ON_TX_REQ_OFS, I2C_SLAVE_CTRL_SLV_TXTRIG_AT_TXMODE_MASK, I2C_SLAVE_CTRL_SLV_TXTRIG_AT_TXMODE_OFS, I2C_SLAVE_CTRL_SLV_TXWAIT_STALE_FIFO_MASK, I2C_SLAVE_CTRL_SLV_TXWAIT_STALE_FIFO_OFS, I2C_SLAVE_CTRL_u::packed_w, and I2C_REGS_s::SLAVE_CTRL.
I2C_SLAVE_ADDR_WRITE()
void I2C_SLAVE_ADDR_WRITE (I2C_REGS_s * registers, uint32_t slv_addr1, uint32_t slv_addr2) inline static
References I2C_SLAVE_ADDR_SLV_ADDR1_MASK, I2C_SLAVE_ADDR_SLV_ADDR1_OFS, I2C_SLAVE_ADDR_SLV_ADDR2_MASK, I2C_SLAVE_ADDR_SLV_ADDR2_OFS, I2C_SLAVE_ADDR_u::packed_w, and I2C_REGS_s::SLAVE_ADDR.
I2C_SLAVE_ACK_CFG_WRITE()
void I2C_SLAVE_ACK_CFG_WRITE (I2C_REGS_s * registers, uint32_t slv_auto_ack_en, uint32_t slv_addr_auto_ack_en) inline static
References I2C_SLAVE_ACK_CFG_SLV_ADDR_AUTO_ACK_EN_MASK, I2C_SLAVE_ACK_CFG_SLV_ADDR_AUTO_ACK_EN_OFS, I2C_SLAVE_ACK_CFG_SLV_AUTO_ACK_EN_MASK, I2C_SLAVE_ACK_CFG_SLV_AUTO_ACK_EN_OFS, I2C_SLAVE_ACK_CFG_u::packed_w, and I2C_REGS_s::SLAVE_ACK_CFG.
I2C_SLAVE_BYTE_ACK_WRITE()
void I2C_SLAVE_BYTE_ACK_WRITE (I2C_REGS_s * registers, uint32_t slv_ackval) inline static
References I2C_SLAVE_BYTE_ACK_SLV_ACKVAL_MASK, I2C_SLAVE_BYTE_ACK_SLV_ACKVAL_OFS, I2C_SLAVE_BYTE_ACK_u::packed_w, and I2C_REGS_s::SLAVE_BYTE_ACK.
I2C_FIFO_CTRL_WRITE()
void I2C_FIFO_CTRL_WRITE (I2C_REGS_s * registers, uint32_t rxfifo_en, uint32_t txfifo_en, uint32_t rxfifo_flush, uint32_t txfifo_flush) inline static
References I2C_REGS_s::FIFO_CTRL, I2C_FIFO_CTRL_RXFIFO_EN_MASK, I2C_FIFO_CTRL_RXFIFO_EN_OFS, I2C_FIFO_CTRL_RXFIFO_FLUSH_MASK, I2C_FIFO_CTRL_RXFIFO_FLUSH_OFS, I2C_FIFO_CTRL_TXFIFO_EN_MASK, I2C_FIFO_CTRL_TXFIFO_EN_OFS, I2C_FIFO_CTRL_TXFIFO_FLUSH_MASK, I2C_FIFO_CTRL_TXFIFO_FLUSH_OFS, and I2C_FIFO_CTRL_u::packed_w.
I2C_TXDATA_N_WRITE()
void I2C_TXDATA_N_WRITE (I2C_REGS_s * registers, uint32_t index, uint32_t txdata) inline static
References I2C_TXDATA_TXDATA_MASK, I2C_TXDATA_TXDATA_OFS, I2C_TXDATA_u::packed_w, and I2C_REGS_s::TXDATA.
I2C_PEC_CTRL_WRITE()
void I2C_PEC_CTRL_WRITE (I2C_REGS_s * registers, uint32_t pec_en) inline static
References I2C_PEC_CTRL_PEC_EN_MASK, I2C_PEC_CTRL_PEC_EN_OFS, I2C_PEC_CTRL_u::packed_w, and I2C_REGS_s::PEC_CTRL.
I2C_MASTER_CFG_WRITE()
void I2C_MASTER_CFG_WRITE (I2C_REGS_s * registers, uint32_t mst_enable, uint32_t mst_clkstretch_en, uint32_t lpbk_mode, uint32_t mst_auto_ack_en, uint32_t mst_addr_mode, uint32_t mst_slv_addr_cfg) inline static
References I2C_MASTER_CFG_LPBK_MODE_MASK, I2C_MASTER_CFG_LPBK_MODE_OFS, I2C_MASTER_CFG_MST_ADDR_MODE_MASK, I2C_MASTER_CFG_MST_ADDR_MODE_OFS, I2C_MASTER_CFG_MST_AUTO_ACK_EN_MASK, I2C_MASTER_CFG_MST_AUTO_ACK_EN_OFS, I2C_MASTER_CFG_MST_CLKSTRETCH_EN_MASK, I2C_MASTER_CFG_MST_CLKSTRETCH_EN_OFS, I2C_MASTER_CFG_MST_ENABLE_MASK, I2C_MASTER_CFG_MST_ENABLE_OFS, I2C_MASTER_CFG_MST_SLV_ADDR_CFG_MASK, I2C_MASTER_CFG_MST_SLV_ADDR_CFG_OFS, I2C_REGS_s::MASTER_CFG, and I2C_MASTER_CFG_u::packed_w.
I2C_MASTER_CTRL_WRITE()
void I2C_MASTER_CTRL_WRITE (I2C_REGS_s * registers, uint32_t mst_cmd_vld, uint32_t mst_burst_len, uint32_t mst_start, uint32_t mst_dir, uint32_t mst_stop, uint32_t mst_rd_on_txempty) inline static
References I2C_MASTER_CTRL_MST_BURST_LEN_MASK, I2C_MASTER_CTRL_MST_BURST_LEN_OFS, I2C_MASTER_CTRL_MST_CMD_VLD_MASK, I2C_MASTER_CTRL_MST_CMD_VLD_OFS, I2C_MASTER_CTRL_MST_DIR_MASK, I2C_MASTER_CTRL_MST_DIR_OFS, I2C_MASTER_CTRL_MST_RD_ON_TXEMPTY_MASK, I2C_MASTER_CTRL_MST_RD_ON_TXEMPTY_OFS, I2C_MASTER_CTRL_MST_START_MASK, I2C_MASTER_CTRL_MST_START_OFS, I2C_MASTER_CTRL_MST_STOP_MASK, I2C_MASTER_CTRL_MST_STOP_OFS, I2C_REGS_s::MASTER_CTRL, and I2C_MASTER_CTRL_u::packed_w.
I2C_MASTER_ACK_VAL_WRITE()
void I2C_MASTER_ACK_VAL_WRITE (I2C_REGS_s * registers, uint32_t mst_ackval) inline static
References I2C_MASTER_ACK_VAL_MST_ACKVAL_MASK, I2C_MASTER_ACK_VAL_MST_ACKVAL_OFS, I2C_REGS_s::MASTER_ACK_VAL, and I2C_MASTER_ACK_VAL_u::packed_w.