My Project: UART_RW_API.h File Reference
UART_RW_API.h File Reference
#include "UART_REGS.h"
Functions
static void UART_PWR_EN_WRITE (UART_REGS_s *registers, uint32_t pwr_en, uint32_t pwr_en_key)
static void UART_RST_CTRL_WRITE (UART_REGS_s *registers, uint32_t rst, uint32_t rst_sts_clr, uint32_t rst_key)
static void UART_CLK_CTRL_WRITE (UART_REGS_s *registers, uint32_t clk_en)
static void UART_CLK_SEL_WRITE (UART_REGS_s *registers, uint32_t clk_sel)
static void UART_CLK_DIV_WRITE (UART_REGS_s *registers, uint32_t clk_div)
static void UART_DBG_CTRL_WRITE (UART_REGS_s *registers, uint32_t run_on_halt, uint32_t soft_stop)
static void UART_INTR_EVENT_CLEAR (UART_REGS_s *registers, uint32_t intr_idx)
static void UART_INTR_EVENT_EN (UART_REGS_s *registers, uint32_t intr_idx)
static void UART_INTR_EVENT_DIS (UART_REGS_s *registers, uint32_t intr_idx)
static void UART_INTR_EVENT_NMI_EN (UART_REGS_s *registers, uint32_t intr_idx)
static void UART_INTR_EVENT_NMI_DIS (UART_REGS_s *registers, uint32_t intr_idx)
static void UART_INTR_SW_SET (UART_REGS_s *registers, uint32_t intr_idx)
static void UART_GENERIC_DMA_RX_EVENT_EN (UART_REGS_s *registers, uint32_t intr_idx)
static void UART_GENERIC_DMA_RX_EVENT_DIS (UART_REGS_s *registers, uint32_t intr_idx)
static void UART_GENERIC_DMA_TX_EVENT_EN (UART_REGS_s *registers, uint32_t intr_idx)
static void UART_GENERIC_DMA_TX_EVENT_DIS (UART_REGS_s *registers, uint32_t intr_idx)
static void UART_CLKCFG_WRITE (UART_REGS_s *registers, uint32_t blck_async, uint32_t async_req_en_key)
static void UART_FIFOLS_WRITE (UART_REGS_s *registers, uint32_t tx_fifo_ls, uint32_t rx_to, uint32_t rx_fifo_ls)
static void UART_CFG_WRITE (UART_REGS_s *registers, uint32_t wrd_len, uint32_t par_en, uint32_t evn_par, uint32_t stck_par, uint32_t stop_bit, uint32_t send_idle)
static void UART_GFCTL_WRITE (UART_REGS_s *registers, uint32_t gf_width)
static void UART_TXDATA_N_WRITE (UART_REGS_s *registers, uint32_t index, uint32_t uart_data)
static void UART_BRDNUM_WRITE (UART_REGS_s *registers, uint32_t num_m)
static void UART_BRDDEN_WRITE (UART_REGS_s *registers, uint32_t den_n)
static void UART_CTRL_WRITE (UART_REGS_s *registers, uint32_t uart_en, uint32_t uart_msb, uint32_t majvote_en, uint32_t fifo_en, uint32_t os, uint32_t loopback_en, uint32_t mode, uint32_t tx_en, uint32_t rx_en, uint32_t tx_out_en, uint32_t tx_out_ctrl, uint32_t cts_en, uint32_t rts_en, uint32_t rts_val)
static void UART_ADDR_WRITE (UART_REGS_s *registers, uint32_t uart_addr)
static void UART_ADDRMASK_WRITE (UART_REGS_s *registers, uint32_t addr_mask)
Function Documentation
UART_PWR_EN_WRITE()
void UART_PWR_EN_WRITE (UART_REGS_s * registers, uint32_t pwr_en, uint32_t pwr_en_key) inline static
References UART_PWR_EN_u::packed_w, UART_REGS_s::PWR_EN, UART_PWR_EN_PWR_EN_KEY_MASK, UART_PWR_EN_PWR_EN_KEY_OFS, UART_PWR_EN_PWR_EN_MASK, and UART_PWR_EN_PWR_EN_OFS.
Referenced by uart_init().
UART_RST_CTRL_WRITE()
void UART_RST_CTRL_WRITE (UART_REGS_s * registers, uint32_t rst, uint32_t rst_sts_clr, uint32_t rst_key) inline static
References UART_RST_CTRL_u::packed_w, UART_REGS_s::RST_CTRL, UART_RST_CTRL_RST_KEY_MASK, UART_RST_CTRL_RST_KEY_OFS, UART_RST_CTRL_RST_MASK, UART_RST_CTRL_RST_OFS, UART_RST_CTRL_RST_STS_CLR_MASK, and UART_RST_CTRL_RST_STS_CLR_OFS.
Referenced by uart_init().
UART_CLK_CTRL_WRITE()
void UART_CLK_CTRL_WRITE (UART_REGS_s * registers, uint32_t clk_en) inline static
References UART_REGS_s::CLK_CTRL, UART_CLK_CTRL_u::packed_w, UART_CLK_CTRL_CLK_EN_MASK, and UART_CLK_CTRL_CLK_EN_OFS.
UART_CLK_SEL_WRITE()
void UART_CLK_SEL_WRITE (UART_REGS_s * registers, uint32_t clk_sel) inline static
References UART_REGS_s::CLK_SEL, UART_CLK_SEL_u::packed_w, UART_CLK_SEL_CLK_SEL_MASK, and UART_CLK_SEL_CLK_SEL_OFS.
UART_CLK_DIV_WRITE()
void UART_CLK_DIV_WRITE (UART_REGS_s * registers, uint32_t clk_div) inline static
References UART_REGS_s::CLK_DIV, UART_CLK_DIV_u::packed_w, UART_CLK_DIV_CLK_DIV_MASK, and UART_CLK_DIV_CLK_DIV_OFS.
UART_DBG_CTRL_WRITE()
void UART_DBG_CTRL_WRITE (UART_REGS_s * registers, uint32_t run_on_halt, uint32_t soft_stop) inline static
References UART_REGS_s::DBG_CTRL, UART_DBG_CTRL_u::packed_w, UART_DBG_CTRL_RUN_ON_HALT_MASK, UART_DBG_CTRL_RUN_ON_HALT_OFS, UART_DBG_CTRL_SOFT_STOP_MASK, and UART_DBG_CTRL_SOFT_STOP_OFS.
UART_INTR_EVENT_CLEAR()
void UART_INTR_EVENT_CLEAR (UART_REGS_s * registers, uint32_t intr_idx) inline static
References UART_REGS_s::INTR_EVENT, and UART_INTR_EVENT_u::packed_w.
UART_INTR_EVENT_EN()
void UART_INTR_EVENT_EN (UART_REGS_s * registers, uint32_t intr_idx) inline static
References UART_REGS_s::INTR_EN0, UART_REGS_s::INTR_EN1, UART_INTR_EN0_u::packed_w, and UART_INTR_EN1_u::packed_w.
UART_INTR_EVENT_DIS()
void UART_INTR_EVENT_DIS (UART_REGS_s * registers, uint32_t intr_idx) inline static
References UART_REGS_s::INTR_EN0, UART_REGS_s::INTR_EN1, UART_INTR_EN0_u::packed_w, and UART_INTR_EN1_u::packed_w.
UART_INTR_EVENT_NMI_EN()
void UART_INTR_EVENT_NMI_EN (UART_REGS_s * registers, uint32_t intr_idx) inline static
References UART_REGS_s::INTR_NMI_EN0, UART_REGS_s::INTR_NMI_EN1, UART_INTR_NMI_EN0_u::packed_w, and UART_INTR_NMI_EN1_u::packed_w.
UART_INTR_EVENT_NMI_DIS()
void UART_INTR_EVENT_NMI_DIS (UART_REGS_s * registers, uint32_t intr_idx) inline static
References UART_REGS_s::INTR_NMI_EN0, UART_REGS_s::INTR_NMI_EN1, UART_INTR_NMI_EN0_u::packed_w, and UART_INTR_NMI_EN1_u::packed_w.
UART_INTR_SW_SET()
void UART_INTR_SW_SET (UART_REGS_s * registers, uint32_t intr_idx) inline static
References UART_REGS_s::INTR_SW_SET, and UART_INTR_SW_SET_u::packed_w.
UART_GENERIC_DMA_RX_EVENT_EN()
void UART_GENERIC_DMA_RX_EVENT_EN (UART_REGS_s * registers, uint32_t intr_idx) inline static
References UART_REGS_s::DMA_RX_EVENT_EN0, UART_REGS_s::DMA_RX_EVENT_EN1, UART_DMA_RX_EVENT_EN0_u::packed_w, and UART_DMA_RX_EVENT_EN1_u::packed_w.
UART_GENERIC_DMA_RX_EVENT_DIS()
void UART_GENERIC_DMA_RX_EVENT_DIS (UART_REGS_s * registers, uint32_t intr_idx) inline static
References UART_REGS_s::DMA_RX_EVENT_EN0, UART_REGS_s::DMA_RX_EVENT_EN1, UART_DMA_RX_EVENT_EN0_u::packed_w, and UART_DMA_RX_EVENT_EN1_u::packed_w.
UART_GENERIC_DMA_TX_EVENT_EN()
void UART_GENERIC_DMA_TX_EVENT_EN (UART_REGS_s * registers, uint32_t intr_idx) inline static
References UART_REGS_s::DMA_TX_EVENT_EN0, UART_REGS_s::DMA_TX_EVENT_EN1, UART_DMA_TX_EVENT_EN0_u::packed_w, and UART_DMA_TX_EVENT_EN1_u::packed_w.
UART_GENERIC_DMA_TX_EVENT_DIS()
void UART_GENERIC_DMA_TX_EVENT_DIS (UART_REGS_s * registers, uint32_t intr_idx) inline static
References UART_REGS_s::DMA_TX_EVENT_EN0, UART_REGS_s::DMA_TX_EVENT_EN1, UART_DMA_TX_EVENT_EN0_u::packed_w, and UART_DMA_TX_EVENT_EN1_u::packed_w.
UART_CLKCFG_WRITE()
void UART_CLKCFG_WRITE (UART_REGS_s * registers, uint32_t blck_async, uint32_t async_req_en_key) inline static
References UART_REGS_s::CLKCFG, UART_CLKCFG_u::packed_w, UART_CLKCFG_ASYNC_REQ_EN_KEY_MASK, UART_CLKCFG_ASYNC_REQ_EN_KEY_OFS, UART_CLKCFG_BLCK_ASYNC_MASK, and UART_CLKCFG_BLCK_ASYNC_OFS.
Referenced by uart_init().
UART_FIFOLS_WRITE()
void UART_FIFOLS_WRITE (UART_REGS_s * registers, uint32_t tx_fifo_ls, uint32_t rx_to, uint32_t rx_fifo_ls) inline static
References UART_REGS_s::FIFOLS, UART_FIFOLS_u::packed_w, UART_FIFOLS_RX_FIFO_LS_MASK, UART_FIFOLS_RX_FIFO_LS_OFS, UART_FIFOLS_RX_TO_MASK, UART_FIFOLS_RX_TO_OFS, UART_FIFOLS_TX_FIFO_LS_MASK, and UART_FIFOLS_TX_FIFO_LS_OFS.
UART_CFG_WRITE()
void UART_CFG_WRITE (UART_REGS_s * registers, uint32_t wrd_len, uint32_t par_en, uint32_t evn_par, uint32_t stck_par, uint32_t stop_bit, uint32_t send_idle) inline static
References UART_REGS_s::CFG, UART_CFG_u::packed_w, UART_CFG_EVN_PAR_MASK, UART_CFG_EVN_PAR_OFS, UART_CFG_PAR_EN_MASK, UART_CFG_PAR_EN_OFS, UART_CFG_SEND_IDLE_MASK, UART_CFG_SEND_IDLE_OFS, UART_CFG_STCK_PAR_MASK, UART_CFG_STCK_PAR_OFS, UART_CFG_STOP_BIT_MASK, UART_CFG_STOP_BIT_OFS, UART_CFG_WRD_LEN_MASK, and UART_CFG_WRD_LEN_OFS.
UART_GFCTL_WRITE()
void UART_GFCTL_WRITE (UART_REGS_s * registers, uint32_t gf_width) inline static
References UART_REGS_s::GFCTL, UART_GFCTL_u::packed_w, UART_GFCTL_GF_WIDTH_MASK, and UART_GFCTL_GF_WIDTH_OFS.
UART_TXDATA_N_WRITE()
void UART_TXDATA_N_WRITE (UART_REGS_s * registers, uint32_t index, uint32_t uart_data) inline static
References UART_TXDATA_u::packed_w, UART_REGS_s::TXDATA, UART_TXDATA_UART_DATA_MASK, and UART_TXDATA_UART_DATA_OFS.
UART_BRDNUM_WRITE()
void UART_BRDNUM_WRITE (UART_REGS_s * registers, uint32_t num_m) inline static
References UART_REGS_s::BRDNUM, UART_BRDNUM_u::packed_w, UART_BRDNUM_NUM_M_MASK, and UART_BRDNUM_NUM_M_OFS.
UART_BRDDEN_WRITE()
void UART_BRDDEN_WRITE (UART_REGS_s * registers, uint32_t den_n) inline static
References UART_REGS_s::BRDDEN, UART_BRDDEN_u::packed_w, UART_BRDDEN_DEN_N_MASK, and UART_BRDDEN_DEN_N_OFS.
UART_CTRL_WRITE()
void UART_CTRL_WRITE (UART_REGS_s * registers, uint32_t uart_en, uint32_t uart_msb, uint32_t majvote_en, uint32_t fifo_en, uint32_t os, uint32_t loopback_en, uint32_t mode, uint32_t tx_en, uint32_t rx_en, uint32_t tx_out_en, uint32_t tx_out_ctrl, uint32_t cts_en, uint32_t rts_en, uint32_t rts_val) inline static
References UART_REGS_s::CTRL, UART_CTRL_u::packed_w, UART_CTRL_CTS_EN_MASK, UART_CTRL_CTS_EN_OFS, UART_CTRL_FIFO_EN_MASK, UART_CTRL_FIFO_EN_OFS, UART_CTRL_LOOPBACK_EN_MASK, UART_CTRL_LOOPBACK_EN_OFS, UART_CTRL_MAJVOTE_EN_MASK, UART_CTRL_MAJVOTE_EN_OFS, UART_CTRL_MODE_MASK, UART_CTRL_MODE_OFS, UART_CTRL_OS_MASK, UART_CTRL_OS_OFS, UART_CTRL_RTS_EN_MASK, UART_CTRL_RTS_EN_OFS, UART_CTRL_RTS_VAL_MASK, UART_CTRL_RTS_VAL_OFS, UART_CTRL_RX_EN_MASK, UART_CTRL_RX_EN_OFS, UART_CTRL_TX_EN_MASK, UART_CTRL_TX_EN_OFS, UART_CTRL_TX_OUT_CTRL_MASK, UART_CTRL_TX_OUT_CTRL_OFS, UART_CTRL_TX_OUT_EN_MASK, UART_CTRL_TX_OUT_EN_OFS, UART_CTRL_UART_EN_MASK, UART_CTRL_UART_EN_OFS, UART_CTRL_UART_MSB_MASK, UART_CTRL_UART_MSB_OFS, and uart_en().
UART_ADDR_WRITE()
void UART_ADDR_WRITE (UART_REGS_s * registers, uint32_t uart_addr) inline static
References UART_REGS_s::ADDR, UART_ADDR_u::packed_w, UART_ADDR_UART_ADDR_MASK, and UART_ADDR_UART_ADDR_OFS.
UART_ADDRMASK_WRITE()
void UART_ADDRMASK_WRITE (UART_REGS_s * registers, uint32_t addr_mask) inline static
References UART_REGS_s::ADDRMASK, UART_ADDRMASK_u::packed_w, UART_ADDRMASK_ADDR_MASK_MASK, and UART_ADDRMASK_ADDR_MASK_OFS.