My Project: event_fabric.c File Reference
event_fabric.c File Reference
#include "event_fabric.h"
Functions
void event_fabric_pub_to_dma_channel_cfg (EVENT_FABRIC_REGS_s *registers, EVENT_FABRIC_DMA_PUB_EVENT_ID_E pub_id, uint32_t chan_id)
void event_fabric_pub_to_sub_channel_cfg (EVENT_FABRIC_REGS_s *registers, EVENT_FABRIC_PUB_ID_E pub_id, EVENT_FABRIC_SUB_ID_E sub_id, EVENT_FABRIC_CHAN_ID_E chan_id)
void get_dma_full_chnl_cfg (EVENT_FABRIC_REGS_s *registers, chnl_cfg *chnl)
void get_event_fabric_full_chnl_cfg (EVENT_FABRIC_REGS_s *registers, chnl_cfg *chnl)
Function Documentation
event_fabric_pub_to_dma_channel_cfg()
void event_fabric_pub_to_dma_channel_cfg (EVENT_FABRIC_REGS_s * registers, EVENT_FABRIC_DMA_PUB_EVENT_ID_E pub_id, uint32_t chan_id)
References EVENT_FABRIC_DMA_PUB_N_WRITE().
event_fabric_pub_to_sub_channel_cfg()
void event_fabric_pub_to_sub_channel_cfg (EVENT_FABRIC_REGS_s * registers, EVENT_FABRIC_PUB_ID_E pub_id, EVENT_FABRIC_SUB_ID_E sub_id, EVENT_FABRIC_CHAN_ID_E chan_id)
References EVENT_FABRIC_GEN_PUB_N_WRITE(), and EVENT_FABRIC_GEN_SUB_N_WRITE().
get_dma_full_chnl_cfg()
void get_dma_full_chnl_cfg (EVENT_FABRIC_REGS_s * registers, chnl_cfg * chnl)
References DMA_CHANNELS, EVENT_FABRIC_REGS_s::DMA_PUB, EVENT_FABRIC_DMA_PUB_u::packed_w, chnl_cfg::pub, and chnl_cfg::sub.
get_event_fabric_full_chnl_cfg()
void get_event_fabric_full_chnl_cfg (EVENT_FABRIC_REGS_s * registers, chnl_cfg * chnl)
References EVENT_FABRIC_CHANNELS, EVENT_FABRIC_NUMBER_OF_PUB, EVENT_FABRIC_NUMBER_OF_SUB, EVENT_FABRIC_REGS_s::GEN_PUB, EVENT_FABRIC_REGS_s::GEN_SUB, EVENT_FABRIC_GEN_PUB_u::packed_w, EVENT_FABRIC_GEN_SUB_u::packed_w, chnl_cfg::pub, and chnl_cfg::sub.