My Project: EVENT_FABRIC_HAL
EVENT_FABRIC_HAL
FD32M0P Definitions » FD32M0P Peripherals » Event Fabric
Data Structures
struct chnl_cfg
Event Fabric Channel Configuration Struct.
Macros
#define GENERIC_FABRIC 0
#define DMA_FABRIC 1
#define DMA_CHANNELS 16
#define EVENT_FABRIC_CHANNELS 15
#define EVENT_FABRIC_NUMBER_OF_PUB 23
#define EVENT_FABRIC_NUMBER_OF_SUB 24
Enumerations
enum EVENT_FABRIC_PUB_ID_E {
EVENT_FABRIC_PUB_ID_ADC_0 = 0 , EVENT_FABRIC_PUB_ID_ADC_1 = 1 , EVENT_FABRIC_PUB_ID_GPIO = 2 , EVENT_FABRIC_PUB_ID_RTC = 3 ,
EVENT_FABRIC_PUB_ID_COMP_0 = 4 , EVENT_FABRIC_PUB_ID_COMP_1 = 5 , EVENT_FABRIC_PUB_ID_COMP_2 = 6 , EVENT_FABRIC_PUB_ID_DAC = 9 ,
EVENT_FABRIC_PUB0_ID_TIM_A_0 = 10 , EVENT_FABRIC_PUB1_ID_TIM_A_0 = 11 , EVENT_FABRIC_PUB0_ID_TIM_A_1 = 12 , EVENT_FABRIC_PUB1_ID_TIM_A_1 = 13 ,
EVENT_FABRIC_PUB0_ID_TIM_G_0 = 14 , EVENT_FABRIC_PUB1_ID_TIM_G_0 = 15 , EVENT_FABRIC_PUB0_ID_TIM_G_1 = 16 , EVENT_FABRIC_PUB1_ID_TIM_G_1 = 17 ,
EVENT_FABRIC_PUB0_ID_TIM_G_2 = 18 , EVENT_FABRIC_PUB1_ID_TIM_G_2 = 19 , EVENT_FABRIC_PUB0_ID_TIM_G_3 = 20 , EVENT_FABRIC_PUB1_ID_TIM_G_3 = 21 ,
EVENT_FABRIC_PUB0_ID_TIM_G_4 = 22 , EVENT_FABRIC_PUB1_ID_TIM_G_4 = 23
}
Event Fabric Publisher ID Enum.
enum EVENT_FABRIC_SUB_ID_E {
EVENT_FABRIC_SUB_ID_ADC_0 = 0 , EVENT_FABRIC_SUB_ID_ADC_1 = 1 , EVENT_FABRIC_SUB0_ID_GPIO = 2 , EVENT_FABRIC_SUB1_ID_GPIO = 3 ,
EVENT_FABRIC_SUB0_ID_COMP_0 = 4 , EVENT_FABRIC_SUB1_ID_COMP_0 = 5 , EVENT_FABRIC_SUB0_ID_COMP_1 = 6 , EVENT_FABRIC_SUB1_ID_COMP_1 = 7 ,
EVENT_FABRIC_SUB0_ID_COMP_2 = 8 , EVENT_FABRIC_SUB1_ID_COMP_2 = 9 , EVENT_FABRIC_SUB0_ID_DAC = 10 , EVENT_FABRIC_SUB0_ID_TIM_A_0 = 11 ,
EVENT_FABRIC_SUB1_ID_TIM_A_0 = 12 , EVENT_FABRIC_SUB0_ID_TIM_A_1 = 13 , EVENT_FABRIC_SUB1_ID_TIM_A_1 = 14 , EVENT_FABRIC_SUB0_ID_TIM_G_0 = 15 ,
EVENT_FABRIC_SUB1_ID_TIM_G_0 = 16 , EVENT_FABRIC_SUB0_ID_TIM_G_1 = 17 , EVENT_FABRIC_SUB1_ID_TIM_G_1 = 18 , EVENT_FABRIC_SUB0_ID_TIM_G_2 = 19 ,
EVENT_FABRIC_SUB1_ID_TIM_G_2 = 20 , EVENT_FABRIC_SUB0_ID_TIM_G_3 = 21 , EVENT_FABRIC_SUB1_ID_TIM_G_3 = 22 , EVENT_FABRIC_SUB0_ID_TIM_G_4 = 23 ,
EVENT_FABRIC_SUB1_ID_TIM_G_4 = 24
}
Event Fabric Subscriber ID Enum.
enum EVENT_FABRIC_CHAN_ID_E {
EVENT_FABRIC_CHAN_ID_DISCONNECT = EVENT_FABRIC_GEN_SUB_CHAN_ID_DISCONNECT , EVENT_FABRIC_CHAN_ID_1 = EVENT_FABRIC_GEN_SUB_CHAN_ID_1 , EVENT_FABRIC_CHAN_ID_2 = EVENT_FABRIC_GEN_SUB_CHAN_ID_2 , EVENT_FABRIC_CHAN_ID_3 = EVENT_FABRIC_GEN_SUB_CHAN_ID_3 ,
EVENT_FABRIC_CHAN_ID_4 = EVENT_FABRIC_GEN_SUB_CHAN_ID_4 , EVENT_FABRIC_CHAN_ID_5 = EVENT_FABRIC_GEN_SUB_CHAN_ID_5 , EVENT_FABRIC_CHAN_ID_6 = EVENT_FABRIC_GEN_SUB_CHAN_ID_6 , EVENT_FABRIC_CHAN_ID_7 = EVENT_FABRIC_GEN_SUB_CHAN_ID_7 ,
EVENT_FABRIC_CHAN_ID_8 = EVENT_FABRIC_GEN_SUB_CHAN_ID_8 , EVENT_FABRIC_CHAN_ID_9 = EVENT_FABRIC_GEN_SUB_CHAN_ID_9 , EVENT_FABRIC_CHAN_ID_10 = EVENT_FABRIC_GEN_SUB_CHAN_ID_10 , EVENT_FABRIC_CHAN_ID_11 = EVENT_FABRIC_GEN_SUB_CHAN_ID_11 ,
EVENT_FABRIC_CHAN_ID_12 = EVENT_FABRIC_GEN_SUB_CHAN_ID_12 , EVENT_FABRIC_CHAN_ID_13 = EVENT_FABRIC_GEN_SUB_CHAN_ID_13 , EVENT_FABRIC_CHAN_ID_14 = EVENT_FABRIC_GEN_SUB_CHAN_ID_14 , EVENT_FABRIC_CHAN_ID_15 = EVENT_FABRIC_GEN_SUB_CHAN_ID_15
}
Event Fabric Channel ID Enum.
Functions
void event_fabric_pub_to_dma_channel_cfg (EVENT_FABRIC_REGS_s *registers, EVENT_FABRIC_DMA_PUB_EVENT_ID_E pub_id, uint32_t chan_id)
Configures a Publisher to a specific DMA Channel.
void event_fabric_pub_to_sub_channel_cfg (EVENT_FABRIC_REGS_s *registers, EVENT_FABRIC_PUB_ID_E pub_id, EVENT_FABRIC_SUB_ID_E sub_id, EVENT_FABRIC_CHAN_ID_E chan_id)
Configures an Event Channel to the specified Publisher and Subscriber Pair.
void get_event_fabric_full_chnl_cfg (EVENT_FABRIC_REGS_s *registers, chnl_cfg *chnl)
Get the current configuration of all Event Channels.
void get_dma_full_chnl_cfg (EVENT_FABRIC_REGS_s *registers, chnl_cfg *chnl)
Get the current configuration of all DMA Channels.
Detailed Description
Data Structure Documentation
chnl_cfg
struct chnl_cfg
Event Fabric Channel Configuration Struct.
Data Fields
EVENT_FABRIC_PUB_ID_E pub
EVENT_FABRIC_SUB_ID_E sub
Macro Definition Documentation
GENERIC_FABRIC
#define GENERIC_FABRIC 0
DMA_FABRIC
#define DMA_FABRIC 1
DMA_CHANNELS
#define DMA_CHANNELS 16
Referenced by get_dma_full_chnl_cfg().
EVENT_FABRIC_CHANNELS
#define EVENT_FABRIC_CHANNELS 15
Referenced by get_event_fabric_full_chnl_cfg().
EVENT_FABRIC_NUMBER_OF_PUB
#define EVENT_FABRIC_NUMBER_OF_PUB 23
Referenced by get_event_fabric_full_chnl_cfg().
EVENT_FABRIC_NUMBER_OF_SUB
#define EVENT_FABRIC_NUMBER_OF_SUB 24
Referenced by get_event_fabric_full_chnl_cfg().
Enumeration Type Documentation
EVENT_FABRIC_PUB_ID_E
enum EVENT_FABRIC_PUB_ID_E
Event Fabric Publisher ID Enum.
Enumerator
EVENT_FABRIC_PUB_ID_ADC_0
0
EVENT_FABRIC_PUB_ID_ADC_1
1
EVENT_FABRIC_PUB_ID_GPIO
2
EVENT_FABRIC_PUB_ID_RTC
3
EVENT_FABRIC_PUB_ID_COMP_0
4
EVENT_FABRIC_PUB_ID_COMP_1
5
EVENT_FABRIC_PUB_ID_COMP_2
6
EVENT_FABRIC_PUB_ID_DAC
9
EVENT_FABRIC_PUB0_ID_TIM_A_0
10
EVENT_FABRIC_PUB1_ID_TIM_A_0
11
EVENT_FABRIC_PUB0_ID_TIM_A_1
12
EVENT_FABRIC_PUB1_ID_TIM_A_1
13
EVENT_FABRIC_PUB0_ID_TIM_G_0
14
EVENT_FABRIC_PUB1_ID_TIM_G_0
15
EVENT_FABRIC_PUB0_ID_TIM_G_1
16
EVENT_FABRIC_PUB1_ID_TIM_G_1
17
EVENT_FABRIC_PUB0_ID_TIM_G_2
18
EVENT_FABRIC_PUB1_ID_TIM_G_2
19
EVENT_FABRIC_PUB0_ID_TIM_G_3
20
EVENT_FABRIC_PUB1_ID_TIM_G_3
21
EVENT_FABRIC_PUB0_ID_TIM_G_4
22
EVENT_FABRIC_PUB1_ID_TIM_G_4
23
EVENT_FABRIC_SUB_ID_E
enum EVENT_FABRIC_SUB_ID_E
Event Fabric Subscriber ID Enum.
Enumerator
EVENT_FABRIC_SUB_ID_ADC_0
0
EVENT_FABRIC_SUB_ID_ADC_1
1
EVENT_FABRIC_SUB0_ID_GPIO
2
EVENT_FABRIC_SUB1_ID_GPIO
3
EVENT_FABRIC_SUB0_ID_COMP_0
4
EVENT_FABRIC_SUB1_ID_COMP_0
5
EVENT_FABRIC_SUB0_ID_COMP_1
6
EVENT_FABRIC_SUB1_ID_COMP_1
7
EVENT_FABRIC_SUB0_ID_COMP_2
8
EVENT_FABRIC_SUB1_ID_COMP_2
9
EVENT_FABRIC_SUB0_ID_DAC
10
EVENT_FABRIC_SUB0_ID_TIM_A_0
11
EVENT_FABRIC_SUB1_ID_TIM_A_0
12
EVENT_FABRIC_SUB0_ID_TIM_A_1
13
EVENT_FABRIC_SUB1_ID_TIM_A_1
14
EVENT_FABRIC_SUB0_ID_TIM_G_0
15
EVENT_FABRIC_SUB1_ID_TIM_G_0
16
EVENT_FABRIC_SUB0_ID_TIM_G_1
17
EVENT_FABRIC_SUB1_ID_TIM_G_1
18
EVENT_FABRIC_SUB0_ID_TIM_G_2
19
EVENT_FABRIC_SUB1_ID_TIM_G_2
20
EVENT_FABRIC_SUB0_ID_TIM_G_3
21
EVENT_FABRIC_SUB1_ID_TIM_G_3
22
EVENT_FABRIC_SUB0_ID_TIM_G_4
23
EVENT_FABRIC_SUB1_ID_TIM_G_4
24
EVENT_FABRIC_CHAN_ID_E
enum EVENT_FABRIC_CHAN_ID_E
Event Fabric Channel ID Enum.
Enumerator
EVENT_FABRIC_CHAN_ID_DISCONNECT
EVENT_FABRIC_GEN_SUB_CHAN_ID_DISCONNECT.
EVENT_FABRIC_CHAN_ID_1
EVENT_FABRIC_GEN_SUB_CHAN_ID_1.
EVENT_FABRIC_CHAN_ID_2
EVENT_FABRIC_GEN_SUB_CHAN_ID_2.
EVENT_FABRIC_CHAN_ID_3
EVENT_FABRIC_GEN_SUB_CHAN_ID_3.
EVENT_FABRIC_CHAN_ID_4
EVENT_FABRIC_GEN_SUB_CHAN_ID_4.
EVENT_FABRIC_CHAN_ID_5
EVENT_FABRIC_GEN_SUB_CHAN_ID_5.
EVENT_FABRIC_CHAN_ID_6
EVENT_FABRIC_GEN_SUB_CHAN_ID_6.
EVENT_FABRIC_CHAN_ID_7
EVENT_FABRIC_GEN_SUB_CHAN_ID_7.
EVENT_FABRIC_CHAN_ID_8
EVENT_FABRIC_GEN_SUB_CHAN_ID_8.
EVENT_FABRIC_CHAN_ID_9
EVENT_FABRIC_GEN_SUB_CHAN_ID_9.
EVENT_FABRIC_CHAN_ID_10
EVENT_FABRIC_GEN_SUB_CHAN_ID_10.
EVENT_FABRIC_CHAN_ID_11
EVENT_FABRIC_GEN_SUB_CHAN_ID_11.
EVENT_FABRIC_CHAN_ID_12
EVENT_FABRIC_GEN_SUB_CHAN_ID_12.
EVENT_FABRIC_CHAN_ID_13
EVENT_FABRIC_GEN_SUB_CHAN_ID_13.
EVENT_FABRIC_CHAN_ID_14
EVENT_FABRIC_GEN_SUB_CHAN_ID_14.
EVENT_FABRIC_CHAN_ID_15
EVENT_FABRIC_GEN_SUB_CHAN_ID_15.
Function Documentation
event_fabric_pub_to_dma_channel_cfg()
void event_fabric_pub_to_dma_channel_cfg (EVENT_FABRIC_REGS_s * registers, EVENT_FABRIC_DMA_PUB_EVENT_ID_E pub_id, uint32_t chan_id) extern
Configures a Publisher to a specific DMA Channel.
Parameters
registers pointer to the EVENT_FABRIC_REGS_s
pub_id Publisher ID needed to be configured
chan_id DMA Channel ID which you want the Publisher to publish an event to
References EVENT_FABRIC_DMA_PUB_N_WRITE().
event_fabric_pub_to_sub_channel_cfg()
void event_fabric_pub_to_sub_channel_cfg (EVENT_FABRIC_REGS_s * registers, EVENT_FABRIC_PUB_ID_E pub_id, EVENT_FABRIC_SUB_ID_E sub_id, EVENT_FABRIC_CHAN_ID_E chan_id) extern
Configures an Event Channel to the specified Publisher and Subscriber Pair.
Parameters
registers pointer to the EVENT_FABRIC_REGS_s
pub_id Publisher ID needed to be configured on specified Event Channel
sub_id Subscriber ID needed to be configured on specified Event Channel
chan_id Event Channel ID on which the Publisher Subscriber pair needs to be configured
References EVENT_FABRIC_GEN_PUB_N_WRITE(), and EVENT_FABRIC_GEN_SUB_N_WRITE().
get_event_fabric_full_chnl_cfg()
void get_event_fabric_full_chnl_cfg (EVENT_FABRIC_REGS_s * registers, chnl_cfg * chnl) extern
Get the current configuration of all Event Channels.
Parameters
registers pointer to the EVENT_FABRIC_REGS_s
chnl channel configuration array of structs having the configuration of all Event channels
References EVENT_FABRIC_CHANNELS, EVENT_FABRIC_NUMBER_OF_PUB, EVENT_FABRIC_NUMBER_OF_SUB, EVENT_FABRIC_REGS_s::GEN_PUB, EVENT_FABRIC_REGS_s::GEN_SUB, EVENT_FABRIC_GEN_PUB_u::packed_w, EVENT_FABRIC_GEN_SUB_u::packed_w, chnl_cfg::pub, and chnl_cfg::sub.
get_dma_full_chnl_cfg()
void get_dma_full_chnl_cfg (EVENT_FABRIC_REGS_s * registers, chnl_cfg * chnl) extern
Get the current configuration of all DMA Channels.
Parameters
registers pointer to the EVENT_FABRIC_REGS_s
chnl channel configuration array of structs having the configuration of all DMA channels
References DMA_CHANNELS, EVENT_FABRIC_REGS_s::DMA_PUB, EVENT_FABRIC_DMA_PUB_u::packed_w, chnl_cfg::pub, and chnl_cfg::sub.