FD32M0P Microcontroller SDK: VREF_HAL
VREF_HAL
FD32M0P Hardware Abstraction Layer
Data Structures
struct vref_cfg_s
VREF Configuration Struct.
Functions
void vref_cfg (VREF_REGS_s *vref_regs, IOMUX_REGS_s *iomux_regs, MCU_CTRL_REGS_s *mcu_regs, IOMUX_PA_REG_s iomux_cfg_struct, vref_cfg_s vref_cfg_struct, uint32_t temp_sense_en)
This function configures VREF.
vref_cfg_s get_vref_cfg (VREF_REGS_s *regs)
This function returns VREF configuration.
Detailed Description
Data Structure Documentation
vref_cfg_s
struct vref_cfg_s
VREF Configuration Struct.
Data Fields
uint32_t enable
uint32_t vref_mode
Function Documentation
vref_cfg()
void vref_cfg (VREF_REGS_s * vref_regs, IOMUX_REGS_s * iomux_regs, MCU_CTRL_REGS_s * mcu_regs, IOMUX_PA_REG_s iomux_cfg_struct, vref_cfg_s vref_cfg_struct, uint32_t temp_sense_en)
This function configures VREF.
Parameters
vref_regs : pointer to the VREF register space
iomux_regs : pointer to the IOMUX register space
mcu_regs : pointer to the MCU register space
iomux_cfg_struct : IOMUX configuration struct
vref_cfg_struct : VREF configuration struct
temp_sense_en : does Temperature sensor configuration
Return values
void
References MCU_CTRL_REGS_s::ANA_SPARE_OUT0, VREF_REGS_s::CTRL, vref_cfg_s::enable, iomux_cfg(), and vref_cfg_s::vref_mode.
Referenced by get_vref_cfg().
get_vref_cfg()
vref_cfg_s get_vref_cfg (VREF_REGS_s * regs)
This function returns VREF configuration.
Parameters
regs : pointer to the DAC register space
Return values
void
References VREF_REGS_s::CTRL, and vref_cfg().