My Project: i2c.h File Reference
i2c.h File Reference
#include "I2C_REGS.h"
#include "I2C_RW_API.h"
#include <stdbool.h>
Data Structures
struct i2c_counter_cfg_t
struct i2c_slv_cfg_t
struct i2c_slv_sts_t
Macros
#define I2C_COUNTER_CFG_DEFAULT_100Khz
#define I2C_SLAVE_CFG_DEFAULT
Functions
void i2c_clk_cfg_set (I2C_REGS_s *regs, I2C_CLK_CTRL_CLKSEL_E clksel, uint8_t clkdiv)
void i2c_mst_enable (I2C_REGS_s *regs)
void i2c_slv_enable (I2C_REGS_s *regs)
void i2c_mst_disable (I2C_REGS_s *regs)
void i2c_slv_disable (I2C_REGS_s *regs)
void i2c_counter_cfg_set (I2C_REGS_s *regs, i2c_counter_cfg_t *i2c_counter_cfg)
void i2c_slv_cfg_set (I2C_REGS_s *regs, i2c_slv_cfg_t *i2c_slv_cfg)
void i2c_glitch_width_cfg_set (I2C_REGS_s *regs, uint8_t glitch_width)
uint8_t i2c_txfifo_fill_nonblocking (I2C_REGS_s *regs, const uint8_t *buffer, uint8_t num_bytes)
void i2c_txfifo_fill_blocking (I2C_REGS_s *regs, const uint8_t *buffer, uint8_t num_bytes)
uint8_t i2c_rxfifo_drain_nonblocking (I2C_REGS_s *regs, uint8_t *buffer, uint8_t num_bytes)
void i2c_rxfifo_drain_blocking (I2C_REGS_s *regs, uint8_t *buffer, uint8_t num_bytes)
bool i2c_slv_rd_wr_sts_get (I2C_REGS_s *regs)
void i2c_slv_sts_get (I2C_REGS_s *regs, i2c_slv_sts_t *i2c_slv_sts)
void i2c_wait_for_slv_start (I2C_REGS_s *regs)
void i2c_wait_for_rx_done (I2C_REGS_s *regs)
void i2c_wait_for_tx_done (I2C_REGS_s *regs)
bool i2c_poll_for_slv_stop (I2C_REGS_s *regs)
void i2c_slv_ackval (I2C_REGS_s *regs, I2C_SLAVE_BYTE_ACK_SLV_ACKVAL_E ackval)
Data Structure Documentation
i2c_counter_cfg_t
struct i2c_counter_cfg_t
Data Fields
uint8_t setup_cnt
uint8_t mst_scl_cnt_high_val
uint8_t mst_scl_cnt_low_val
uint8_t mst_scl_start_cnt
uint8_t mst_sda_stop_cnt
uint8_t mst_stop_start_buffer_cnt
uint8_t mst_restart_setup_cnt
uint32_t mst_max_clkstretch_cnt
uint32_t slv_max_clkstretch_cnt
uint32_t smbus_timeout_cnt
i2c_slv_cfg_t
struct i2c_slv_cfg_t
Data Fields
I2C_SLAVE_CTRL_SLV_ADDR_MODE_E slv_addr_mode
bool slv_low_pwr_wakeup_en
bool slv_def_dev_addr_en
bool slv_alres_addr_en
bool slv_def_host_addr_en
bool slv_txtrig_at_txmode
bool slv_clkstretch_en
bool slv_gencall_en
bool slv_addr2_en
uint8_t slv_addr2_mask
I2C_SLAVE_CTRL_SLV_TXWAIT_STALE_FIFO_E slv_txwait_stale_fifo
I2C_SLAVE_CTRL_SLV_TXEMPTY_INTR_ON_TX_REQ_E slv_txempty_intr_on_tx_req
uint16_t slv_addr1
uint16_t slv_addr2
bool slv_auto_ack_en
bool slv_addr_auto_ack_en
bool i2c_pec_en
bool rxfifo_en
bool txfifo_en
i2c_slv_sts_t
struct i2c_slv_sts_t
Data Fields
bool slv_rx_req
bool slv_tx_req
bool slv_addr2_sel
bool quick_cmd_sts
bool quick_cmd_rw
bool slv_addr_match
bool slv_stale_txfifo
bool slv_txmode
bool slv_rxmode
bool slv_busbsy
Macro Definition Documentation
I2C_COUNTER_CFG_DEFAULT_100Khz
#define I2C_COUNTER_CFG_DEFAULT_100Khz
Value:
    {                                       \
    .setup_cnt = 7                  ,\
    .mst_scl_cnt_high_val = 64      ,\
    .mst_scl_cnt_low_val = 78       ,\
    .mst_scl_start_cnt = 66         ,\
    .mst_sda_stop_cnt = 66          ,\
    .mst_stop_start_buffer_cnt = 78 ,\
    .mst_restart_setup_cnt = 78     ,\
    .mst_max_clkstretch_cnt = 5000   ,\
    .slv_max_clkstretch_cnt = 5000   ,\
    .smbus_timeout_cnt = 5000        \
}
I2C_SLAVE_CFG_DEFAULT
#define I2C_SLAVE_CFG_DEFAULT
Value:
    {                                       \
    .slv_addr_mode = I2C_SLAVE_CTRL_SLV_ADDR_MODE_7_BIT ,\
    .slv_low_pwr_wakeup_en = 1                                                           ,\
    .slv_def_dev_addr_en = 0                                                             ,\
    .slv_alres_addr_en = 0                                                               ,\
    .slv_def_host_addr_en = 0                                                            ,\
    .slv_txtrig_at_txmode = 0                                                            ,\
    .slv_clkstretch_en = 1                                                               ,\
    .slv_gencall_en = 0                                                                  ,\
    .slv_addr2_en = 0                                                                    ,\
    .slv_addr2_mask = 0                                                                  ,\
    .slv_txwait_stale_fifo = I2C_SLAVE_CTRL_SLV_TXWAIT_STALE_FIFO_NOT_TREATED_AS_EMPTY   ,\
    .slv_txempty_intr_on_tx_req = I2C_SLAVE_CTRL_SLV_TXEMPTY_INTR_ON_TX_REQ_AGNOSTIC     ,\
    .slv_addr1 = 0x55                                                                    ,\
    .slv_addr2 = 0x52                                                                    ,\
    .slv_auto_ack_en = 0                                                                 ,\
    .slv_addr_auto_ack_en = 0                                                            ,\
    .i2c_pec_en = 0                                                                      ,\
    .rxfifo_en = 0                                                                       ,\
    .txfifo_en = 0                                                                        \
}
Function Documentation
i2c_clk_cfg_set()
void i2c_clk_cfg_set (I2C_REGS_s * regs, I2C_CLK_CTRL_CLKSEL_E clksel, uint8_t clkdiv)
References I2C_REGS_s::CLK_CTRL.
i2c_mst_enable()
void i2c_mst_enable (I2C_REGS_s * regs)
References I2C_REGS_s::MASTER_CFG.
i2c_slv_enable()
void i2c_slv_enable (I2C_REGS_s * regs)
References I2C_REGS_s::SLAVE_CTRL.
i2c_mst_disable()
void i2c_mst_disable (I2C_REGS_s * regs)
References I2C_REGS_s::MASTER_CFG.
i2c_slv_disable()
void i2c_slv_disable (I2C_REGS_s * regs)
References I2C_REGS_s::SLAVE_CTRL.
i2c_counter_cfg_set()
void i2c_counter_cfg_set (I2C_REGS_s * regs, i2c_counter_cfg_t * i2c_counter_cfg)
References I2C_REGS_s::CLK_CTRL, I2C_REGS_s::MASTER_CLKSTRETCH_CNT, I2C_REGS_s::MASTER_SCL_GEN, I2C_REGS_s::MASTER_TIMING_CONSTRAINT, i2c_counter_cfg_t::mst_max_clkstretch_cnt, i2c_counter_cfg_t::mst_restart_setup_cnt, i2c_counter_cfg_t::mst_scl_cnt_high_val, i2c_counter_cfg_t::mst_scl_cnt_low_val, i2c_counter_cfg_t::mst_scl_start_cnt, i2c_counter_cfg_t::mst_sda_stop_cnt, i2c_counter_cfg_t::mst_stop_start_buffer_cnt, i2c_counter_cfg_t::setup_cnt, I2C_REGS_s::SLAVE_CLKSTRETCH_CNT, i2c_counter_cfg_t::slv_max_clkstretch_cnt, I2C_REGS_s::SMBUS_TIMEOUT_CNT, and i2c_counter_cfg_t::smbus_timeout_cnt.
i2c_slv_cfg_set()
void i2c_slv_cfg_set (I2C_REGS_s * regs, i2c_slv_cfg_t * i2c_slv_cfg)
References I2C_REGS_s::FIFO_CTRL, i2c_slv_cfg_t::i2c_pec_en, I2C_REGS_s::PEC_CTRL, i2c_slv_cfg_t::rxfifo_en, I2C_REGS_s::SLAVE_ACK_CFG, I2C_REGS_s::SLAVE_ADDR, I2C_REGS_s::SLAVE_CTRL, i2c_slv_cfg_t::slv_addr1, i2c_slv_cfg_t::slv_addr2, i2c_slv_cfg_t::slv_addr2_en, i2c_slv_cfg_t::slv_addr2_mask, i2c_slv_cfg_t::slv_addr_auto_ack_en, i2c_slv_cfg_t::slv_addr_mode, i2c_slv_cfg_t::slv_alres_addr_en, i2c_slv_cfg_t::slv_auto_ack_en, i2c_slv_cfg_t::slv_clkstretch_en, i2c_slv_cfg_t::slv_def_dev_addr_en, i2c_slv_cfg_t::slv_def_host_addr_en, i2c_slv_cfg_t::slv_gencall_en, i2c_slv_cfg_t::slv_low_pwr_wakeup_en, i2c_slv_cfg_t::slv_txempty_intr_on_tx_req, i2c_slv_cfg_t::slv_txtrig_at_txmode, i2c_slv_cfg_t::slv_txwait_stale_fifo, and i2c_slv_cfg_t::txfifo_en.
i2c_glitch_width_cfg_set()
void i2c_glitch_width_cfg_set (I2C_REGS_s * regs, uint8_t glitch_width)
References I2C_REGS_s::GLITCH_FILTER_CFG.
i2c_txfifo_fill_nonblocking()
uint8_t i2c_txfifo_fill_nonblocking (I2C_REGS_s * regs, const uint8_t * buffer, uint8_t num_bytes)
References I2C_REGS_s::FIFO_STS, I2C_TXDATA_u::packed_byte, and I2C_REGS_s::TXDATA.
i2c_txfifo_fill_blocking()
void i2c_txfifo_fill_blocking (I2C_REGS_s * regs, const uint8_t * buffer, uint8_t num_bytes)
References I2C_REGS_s::FIFO_STS, I2C_TXDATA_u::packed_byte, and I2C_REGS_s::TXDATA.
i2c_rxfifo_drain_nonblocking()
uint8_t i2c_rxfifo_drain_nonblocking (I2C_REGS_s * regs, uint8_t * buffer, uint8_t num_bytes)
References I2C_REGS_s::FIFO_STS, I2C_RXDATA_u::packed_byte, and I2C_REGS_s::RXDATA.
i2c_rxfifo_drain_blocking()
void i2c_rxfifo_drain_blocking (I2C_REGS_s * regs, uint8_t * buffer, uint8_t num_bytes)
References I2C_REGS_s::FIFO_STS, I2C_RXDATA_u::packed_byte, and I2C_REGS_s::RXDATA.
i2c_slv_rd_wr_sts_get()
bool i2c_slv_rd_wr_sts_get (I2C_REGS_s * regs)
References I2C_REGS_s::SPARE_STS.
i2c_slv_sts_get()
void i2c_slv_sts_get (I2C_REGS_s * regs, i2c_slv_sts_t * i2c_slv_sts)
References i2c_slv_sts_t::quick_cmd_rw, i2c_slv_sts_t::quick_cmd_sts, I2C_REGS_s::SLAVE_STS, i2c_slv_sts_t::slv_addr2_sel, i2c_slv_sts_t::slv_addr_match, i2c_slv_sts_t::slv_busbsy, i2c_slv_sts_t::slv_rx_req, i2c_slv_sts_t::slv_rxmode, i2c_slv_sts_t::slv_stale_txfifo, i2c_slv_sts_t::slv_tx_req, and i2c_slv_sts_t::slv_txmode.
i2c_wait_for_slv_start()
void i2c_wait_for_slv_start (I2C_REGS_s * regs)
References I2C_INTR_EVENT_CLEAR(), I2C_INTR_EVENT_SLV_START_IDX, and I2C_REGS_s::INTR_EVENT.
i2c_wait_for_rx_done()
void i2c_wait_for_rx_done (I2C_REGS_s * regs)
References I2C_INTR_EVENT_CLEAR(), I2C_INTR_EVENT_RX_DONE_IDX, and I2C_REGS_s::INTR_EVENT.
i2c_wait_for_tx_done()
void i2c_wait_for_tx_done (I2C_REGS_s * regs)
References I2C_INTR_EVENT_CLEAR(), I2C_INTR_EVENT_TX_DONE_IDX, and I2C_REGS_s::INTR_EVENT.
i2c_poll_for_slv_stop()
bool i2c_poll_for_slv_stop (I2C_REGS_s * regs)
References I2C_INTR_EVENT_CLEAR(), I2C_INTR_EVENT_SLV_STOP_IDX, and I2C_REGS_s::INTR_EVENT.
i2c_slv_ackval()
void i2c_slv_ackval (I2C_REGS_s * regs, I2C_SLAVE_BYTE_ACK_SLV_ACKVAL_E ackval)
References I2C_REGS_s::SLAVE_BYTE_ACK.