My Project: retarget.c File Reference
retarget.c File Reference
#include <stdio.h>
#include <time.h>
#include <rt_misc.h>
Functions
unsigned char UartGetc (void)
unsigned char UartPutc (unsigned char my_ch)
int fputc (int ch, FILE *f)
int fgetc (FILE *f)
int ferror (FILE *f)
void _ttywrch (int ch)
void _sys_exit (int return_code)
Variables
FILE __stdout
FILE __stdin
Function Documentation
UartGetc()
unsigned char UartGetc (void) extern
Referenced by fgetc().
UartPutc()
unsigned char UartPutc (unsigned char my_ch) extern
Referenced by __attribute__(), _ttywrch(), fgetc(), fputc(), UartEndSimulation(), UartFail(), UartPass(), and UartPuts().
fputc()
int fputc (int ch, FILE * f)
References UartPutc().
fgetc()
int fgetc (FILE * f)
References UartGetc(), and UartPutc().
ferror()
int ferror (FILE * f)
_ttywrch()
void _ttywrch (int ch)
References UartPutc().
_sys_exit()
void _sys_exit (int return_code)
Variable Documentation
__stdout
FILE __stdout
__stdin
FILE __stdin