FD32M0P Microcontroller SDK: romtable_tests.c File Reference
romtable_tests.c File Reference
#include "CMSDK_CM0plus.h"
#include "core_cm0plus.h"
#include <stdio.h>
#include "uart_stdout.h"
#include "mcu_debugtester_interface.h"
#include "CMSDK_driver.h"
#include "config_id.h"
#include "debugtester_functions.h"
#include "romtable_tests.h"
Macros
#define COMPMAX 10
Functions
void FollowCoreSightPointer (uint32_t cs_pointer)
uint32_t CheckVal (char *name, uint32_t actual, uint32_t expected)
void CheckHex (char *name, uint32_t actual, uint32_t expected)
void CheckPresence (char *name, uint32_t actual, uint32_t expected)
void InitComponentsList (void)
void ReportResults (void)
CS_Type * FindComponent (uint32_t base_address)
void GetCoreSightIDs (CS_Type *comp_ptr)
void CheckDisplayCID (CS_Type *comp_ptr)
void CheckDisplayPID (CS_Type *comp_ptr)
void DisplayDecodedPID (CS_Type *comp_ptr)
uint32_t LookupARMCSPart (uint32_t)
int main (void)
Variables
CS_Type Components [COMPMAX]
uint32_t NumRomTables = 0
uint32_t Errors = 0
Macro Definition Documentation
COMPMAX
#define COMPMAX 10
Referenced by FindComponent(), InitComponentsList(), and ReportResults().
Function Documentation
FollowCoreSightPointer()
void FollowCoreSightPointer (uint32_t cs_pointer)
References CheckDisplayCID(), CheckDisplayPID(), Errors, FindComponent(), FollowCoreSightPointer(), and GetCoreSightIDs().
Referenced by FollowCoreSightPointer(), and main().
CheckVal()
uint32_t CheckVal (char * name, uint32_t actual, uint32_t expected)
References CheckHex().
CheckHex()
void CheckHex (char * name, uint32_t actual, uint32_t expected)
References Errors.
Referenced by CheckVal().
CheckPresence()
void CheckPresence (char * name, uint32_t actual, uint32_t expected)
References Errors.
InitComponentsList()
void InitComponentsList (void)
References COMPMAX, and Components.
Referenced by main().
ReportResults()
void ReportResults (void)
References COMPMAX, Components, and Errors.
Referenced by main().
FindComponent()
CS_Type * FindComponent (uint32_t base_address)
References COMPMAX, Components, and Errors.
Referenced by FollowCoreSightPointer().
GetCoreSightIDs()
void GetCoreSightIDs (CS_Type * comp_ptr)
References ARM_JEP_CONT, ARM_JEP_ID, and NumRomTables.
Referenced by FollowCoreSightPointer().
CheckDisplayCID()
void CheckDisplayCID (CS_Type * comp_ptr)
Referenced by FollowCoreSightPointer().
CheckDisplayPID()
void CheckDisplayPID (CS_Type * comp_ptr)
References DisplayDecodedPID(), EXPECTED_CUST_JEP_CONT, EXPECTED_CUST_JEP_ID, and LookupARMCSPart().
Referenced by FollowCoreSightPointer().
DisplayDecodedPID()
void DisplayDecodedPID (CS_Type * comp_ptr)
Referenced by CheckDisplayPID().
LookupARMCSPart()
uint32_t LookupARMCSPart (uint32_t partnum)
References ARMCSParts, and NumARMCSParts.
Referenced by CheckDisplayPID().
main()
int main (void)
References Errors, EXPECTED_DBG, EXPECTED_JTAGnSW, FollowCoreSightPointer(), InitComponentsList(), MCU_CPU_NAME, ReportResults(), TEST_PASS, and UartStdOutInit().
Variable Documentation
Components
CS_Type Components[COMPMAX]
Referenced by FindComponent(), InitComponentsList(), and ReportResults().
NumRomTables
uint32_t NumRomTables = 0
Referenced by GetCoreSightIDs().
Errors
uint32_t Errors = 0
Referenced by CheckHex(), CheckPresence(), FindComponent(), FollowCoreSightPointer(), main(), and ReportResults().