My Project: uart_stdout_mcu.h File Reference
uart_stdout_mcu.h File Reference
#include "FD32M0P.h"
#include "uart.h"
Macros
#define UART_STDIO UART0_REGS
#define STDIO_BAUD_RATE 0
Functions
void UartStdOutInit (void)
__attribute__ ((section(".sram_code"))) void UartPuts(const char *data_char_arr)
void UartEndSimulation (void)
void UartPass (void)
void UartFail (void)
void itoa_mcu (uint32_t value, char *str, int base)
void print_int_var (const char *prefix, int var, bool is_hex)
Macro Definition Documentation
UART_STDIO
#define UART_STDIO UART0_REGS
Referenced by __attribute__(), UartPuts(), and UartStdOutInit().
STDIO_BAUD_RATE
#define STDIO_BAUD_RATE 0
Referenced by UartStdOutInit().
Function Documentation
UartStdOutInit()
void UartStdOutInit (void)
References STDIO_BAUD_RATE, SystemFrequency, uart_cfg(), UART_CFG_STOP_BIT_ONE, UART_CFG_WRD_LEN_8_BITS, UART_CLK_SEL_CLK_APB, UART_CTRL_OS_FACTOR_3, UART_CTRL_TX_EN_HW, UART_CTRL_UART_MSB_LAST, uart_en(), uart_init(), and UART_STDIO.
Referenced by main().
__attribute__()
__attribute__ ((section(".sram_code"))) const
References __attribute__(), UART_STDIO, and UartPutc().
UartEndSimulation()
void UartEndSimulation (void)
References UartPutc().
UartPass()
void UartPass (void)
References UartPutc().
UartFail()
void UartFail (void)
References UartPutc().
itoa_mcu()
void itoa_mcu (uint32_t value, char * str, int base)
Lightweight itoa implementation Converts an integer to a null-terminated string
Parameters
value The integer value to convert
str Pointer to buffer that receives the result (must be large enough)
base Numerical base for conversion (16, 10)
Referenced by print_int_var().
print_int_var()
void print_int_var (const char * prefix, int var, bool is_hex)
References itoa_mcu(), and UartPuts().