My Project: vref.h File Reference
vref.h File Reference
#include "VREF_REGS.h"
#include "VREF_RW_API.h"
#include "IOMUX_REGS.h"
#include "IOMUX_RW_API.h"
#include "GPIO_REGS.h"
#include "GPIO_RW_API.h"
#include "MCU_CTRL_REGS.h"
#include "MCU_CTRL_RW_API.h"
Data Structures
struct vref_cfg_s
VREF Configuration Struct.
Functions
void vref_cfg (VREF_REGS_s *regs, IOMUX_REGS_s *iomux_regs, MCU_CTRL_REGS_s *mcu_regs, IOMUX_PA_REG_s iomux_cfg_struct, vref_cfg_s vref_cfg_struct, uint32_t temp_sense_en)
This function configures VREF.
vref_cfg_s get_vref_cfg (VREF_REGS_s *regs)
This function returns VREF configuration.
Data Structure Documentation
vref_cfg_s
struct vref_cfg_s
VREF Configuration Struct.
Data Fields
uint32_t enable
uint32_t vref_mode
Function Documentation
vref_cfg()
void vref_cfg (VREF_REGS_s * regs, IOMUX_REGS_s * iomux_regs, MCU_CTRL_REGS_s * mcu_regs, IOMUX_PA_REG_s iomux_cfg_struct, vref_cfg_s vref_cfg_struct, uint32_t temp_sense_en)
This function configures VREF.
Parameters
vref_regs : pointer to the DAC register space
iomux_regs : pointer to the DAC register space
mcu_regs : pointer to the DAC register space
iomux_cfg_struct : IOMUX configuration struct
vref_cfg_struct : VREF configuration struct
temp_sense_en : does Temperature sensor configuration
Return values
void
References MCU_CTRL_REGS_s::ANA_SPARE_OUT0, VREF_REGS_s::CTRL, vref_cfg_s::enable, iomux_cfg(), and vref_cfg_s::vref_mode.
Referenced by get_vref_cfg().
get_vref_cfg()
vref_cfg_s get_vref_cfg (VREF_REGS_s * regs)
This function returns VREF configuration.
Parameters
vref_regs : pointer to the DAC register space
Return values
void
References VREF_REGS_s::CTRL, and vref_cfg().