#include "TIMER_TIMG_NUM_INPUT2_REGS.h"

static inline void TIMER_TIMG_NUM_INPUT2_DESC_WRITE(TIMER_TIMG_NUM_INPUT2_REGS_s * registers, uint32_t module_type, uint32_t modue_subtype, uint32_t major_rev, uint32_t minor_rev) {
    registers->DESC.packed_w =  + ((module_type<<TIMER_TIMG_NUM_INPUT2_DESC_module_type_OFS)&TIMER_TIMG_NUM_INPUT2_DESC_module_type_MASK) + ((modue_subtype<<TIMER_TIMG_NUM_INPUT2_DESC_modue_subtype_OFS)&TIMER_TIMG_NUM_INPUT2_DESC_modue_subtype_MASK) + ((major_rev<<TIMER_TIMG_NUM_INPUT2_DESC_major_rev_OFS)&TIMER_TIMG_NUM_INPUT2_DESC_major_rev_MASK) + ((minor_rev<<TIMER_TIMG_NUM_INPUT2_DESC_minor_rev_OFS)&TIMER_TIMG_NUM_INPUT2_DESC_minor_rev_MASK);
}

static inline void TIMER_TIMG_NUM_INPUT2_PWR_EN_WRITE(TIMER_TIMG_NUM_INPUT2_REGS_s * registers, uint32_t pwr_en, uint32_t pwr_en_key) {
    registers->PWR_EN.packed_w =  + ((pwr_en<<TIMER_TIMG_NUM_INPUT2_PWR_EN_pwr_en_OFS)&TIMER_TIMG_NUM_INPUT2_PWR_EN_pwr_en_MASK) + ((pwr_en_key<<TIMER_TIMG_NUM_INPUT2_PWR_EN_pwr_en_key_OFS)&TIMER_TIMG_NUM_INPUT2_PWR_EN_pwr_en_key_MASK);
}

static inline void TIMER_TIMG_NUM_INPUT2_RST_CTRL_WRITE(TIMER_TIMG_NUM_INPUT2_REGS_s * registers, uint32_t rst, uint32_t rst_sts_clr, uint32_t rst_key) {
    registers->RST_CTRL.packed_w =  + ((rst<<TIMER_TIMG_NUM_INPUT2_RST_CTRL_rst_OFS)&TIMER_TIMG_NUM_INPUT2_RST_CTRL_rst_MASK) + ((rst_sts_clr<<TIMER_TIMG_NUM_INPUT2_RST_CTRL_rst_sts_clr_OFS)&TIMER_TIMG_NUM_INPUT2_RST_CTRL_rst_sts_clr_MASK) + ((rst_key<<TIMER_TIMG_NUM_INPUT2_RST_CTRL_rst_key_OFS)&TIMER_TIMG_NUM_INPUT2_RST_CTRL_rst_key_MASK);
}

static inline void TIMER_TIMG_NUM_INPUT2_RST_STS_WRITE(TIMER_TIMG_NUM_INPUT2_REGS_s * registers, uint32_t rst_sts) {
    registers->RST_STS.packed_w =  + ((rst_sts<<TIMER_TIMG_NUM_INPUT2_RST_STS_rst_sts_OFS)&TIMER_TIMG_NUM_INPUT2_RST_STS_rst_sts_MASK);
}

static inline void TIMER_TIMG_NUM_INPUT2_CLK_CTRL_WRITE(TIMER_TIMG_NUM_INPUT2_REGS_s * registers, uint32_t clk_en) {
    registers->CLK_CTRL.packed_w =  + ((clk_en<<TIMER_TIMG_NUM_INPUT2_CLK_CTRL_clk_en_OFS)&TIMER_TIMG_NUM_INPUT2_CLK_CTRL_clk_en_MASK);
}

static inline void TIMER_TIMG_NUM_INPUT2_INTR_STS_WRITE(TIMER_TIMG_NUM_INPUT2_REGS_s * registers, uint32_t intr_first) {
    registers->INTR_STS.packed_w =  + ((intr_first<<TIMER_TIMG_NUM_INPUT2_INTR_STS_intr_first_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_STS_intr_first_MASK);
}

static inline void TIMER_TIMG_NUM_INPUT2_INTR_EVENT_WRITE(TIMER_TIMG_NUM_INPUT2_REGS_s * registers, uint32_t ctr_zero, uint32_t ctr_load, uint32_t ccd_0, uint32_t ccu_0, uint32_t ccd_1, uint32_t ccu_1, uint32_t ccd_2, uint32_t ccu_2, uint32_t ccd_3, uint32_t ccu_3, uint32_t ccd_4, uint32_t ccu_4, uint32_t ccd_5, uint32_t ccu_5, uint32_t fault, uint32_t trig_ov, uint32_t rctr_zero, uint32_t qei_ctr_dc, uint32_t qei_err) {
    registers->INTR_EVENT.packed_w =  + ((ctr_zero<<TIMER_TIMG_NUM_INPUT2_INTR_EVENT_ctr_zero_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_EVENT_ctr_zero_MASK) + ((ctr_load<<TIMER_TIMG_NUM_INPUT2_INTR_EVENT_ctr_load_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_EVENT_ctr_load_MASK) + ((ccd_0<<TIMER_TIMG_NUM_INPUT2_INTR_EVENT_ccd_0_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_EVENT_ccd_0_MASK) + ((ccu_0<<TIMER_TIMG_NUM_INPUT2_INTR_EVENT_ccu_0_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_EVENT_ccu_0_MASK) + ((ccd_1<<TIMER_TIMG_NUM_INPUT2_INTR_EVENT_ccd_1_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_EVENT_ccd_1_MASK) + ((ccu_1<<TIMER_TIMG_NUM_INPUT2_INTR_EVENT_ccu_1_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_EVENT_ccu_1_MASK) + ((ccd_2<<TIMER_TIMG_NUM_INPUT2_INTR_EVENT_ccd_2_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_EVENT_ccd_2_MASK) + ((ccu_2<<TIMER_TIMG_NUM_INPUT2_INTR_EVENT_ccu_2_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_EVENT_ccu_2_MASK) + ((ccd_3<<TIMER_TIMG_NUM_INPUT2_INTR_EVENT_ccd_3_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_EVENT_ccd_3_MASK) + ((ccu_3<<TIMER_TIMG_NUM_INPUT2_INTR_EVENT_ccu_3_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_EVENT_ccu_3_MASK) + ((ccd_4<<TIMER_TIMG_NUM_INPUT2_INTR_EVENT_ccd_4_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_EVENT_ccd_4_MASK) + ((ccu_4<<TIMER_TIMG_NUM_INPUT2_INTR_EVENT_ccu_4_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_EVENT_ccu_4_MASK) + ((ccd_5<<TIMER_TIMG_NUM_INPUT2_INTR_EVENT_ccd_5_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_EVENT_ccd_5_MASK) + ((ccu_5<<TIMER_TIMG_NUM_INPUT2_INTR_EVENT_ccu_5_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_EVENT_ccu_5_MASK) + ((fault<<TIMER_TIMG_NUM_INPUT2_INTR_EVENT_fault_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_EVENT_fault_MASK) + ((trig_ov<<TIMER_TIMG_NUM_INPUT2_INTR_EVENT_trig_ov_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_EVENT_trig_ov_MASK) + ((rctr_zero<<TIMER_TIMG_NUM_INPUT2_INTR_EVENT_rctr_zero_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_EVENT_rctr_zero_MASK) + ((qei_ctr_dc<<TIMER_TIMG_NUM_INPUT2_INTR_EVENT_qei_ctr_dc_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_EVENT_qei_ctr_dc_MASK) + ((qei_err<<TIMER_TIMG_NUM_INPUT2_INTR_EVENT_qei_err_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_EVENT_qei_err_MASK);
}

static inline void TIMER_TIMG_NUM_INPUT2_INTR_EN_0_WRITE(TIMER_TIMG_NUM_INPUT2_REGS_s * registers, uint32_t ctr_zero_en, uint32_t ctr_load_en, uint32_t ccd_0_en, uint32_t ccu_0_en, uint32_t ccd_1_en, uint32_t ccu_1_en, uint32_t ccd_2_en, uint32_t ccu_2_en, uint32_t ccd_3_en, uint32_t ccu_3_en, uint32_t ccd_4_en, uint32_t ccu_4_en, uint32_t ccd_5_en, uint32_t ccu_5_en, uint32_t fault_en, uint32_t trig_ov_en) {
    registers->INTR_EN_0.packed_w =  + ((ctr_zero_en<<TIMER_TIMG_NUM_INPUT2_INTR_EN_0_ctr_zero_en_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_EN_0_ctr_zero_en_MASK) + ((ctr_load_en<<TIMER_TIMG_NUM_INPUT2_INTR_EN_0_ctr_load_en_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_EN_0_ctr_load_en_MASK) + ((ccd_0_en<<TIMER_TIMG_NUM_INPUT2_INTR_EN_0_ccd_0_en_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_EN_0_ccd_0_en_MASK) + ((ccu_0_en<<TIMER_TIMG_NUM_INPUT2_INTR_EN_0_ccu_0_en_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_EN_0_ccu_0_en_MASK) + ((ccd_1_en<<TIMER_TIMG_NUM_INPUT2_INTR_EN_0_ccd_1_en_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_EN_0_ccd_1_en_MASK) + ((ccu_1_en<<TIMER_TIMG_NUM_INPUT2_INTR_EN_0_ccu_1_en_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_EN_0_ccu_1_en_MASK) + ((ccd_2_en<<TIMER_TIMG_NUM_INPUT2_INTR_EN_0_ccd_2_en_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_EN_0_ccd_2_en_MASK) + ((ccu_2_en<<TIMER_TIMG_NUM_INPUT2_INTR_EN_0_ccu_2_en_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_EN_0_ccu_2_en_MASK) + ((ccd_3_en<<TIMER_TIMG_NUM_INPUT2_INTR_EN_0_ccd_3_en_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_EN_0_ccd_3_en_MASK) + ((ccu_3_en<<TIMER_TIMG_NUM_INPUT2_INTR_EN_0_ccu_3_en_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_EN_0_ccu_3_en_MASK) + ((ccd_4_en<<TIMER_TIMG_NUM_INPUT2_INTR_EN_0_ccd_4_en_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_EN_0_ccd_4_en_MASK) + ((ccu_4_en<<TIMER_TIMG_NUM_INPUT2_INTR_EN_0_ccu_4_en_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_EN_0_ccu_4_en_MASK) + ((ccd_5_en<<TIMER_TIMG_NUM_INPUT2_INTR_EN_0_ccd_5_en_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_EN_0_ccd_5_en_MASK) + ((ccu_5_en<<TIMER_TIMG_NUM_INPUT2_INTR_EN_0_ccu_5_en_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_EN_0_ccu_5_en_MASK) + ((fault_en<<TIMER_TIMG_NUM_INPUT2_INTR_EN_0_fault_en_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_EN_0_fault_en_MASK) + ((trig_ov_en<<TIMER_TIMG_NUM_INPUT2_INTR_EN_0_trig_ov_en_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_EN_0_trig_ov_en_MASK);
}

static inline void TIMER_TIMG_NUM_INPUT2_INTR_EN_1_WRITE(TIMER_TIMG_NUM_INPUT2_REGS_s * registers, uint32_t rctr_zero_en, uint32_t qei_ctr_dc_en, uint32_t qei_err_en) {
    registers->INTR_EN_1.packed_w =  + ((rctr_zero_en<<TIMER_TIMG_NUM_INPUT2_INTR_EN_1_rctr_zero_en_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_EN_1_rctr_zero_en_MASK) + ((qei_ctr_dc_en<<TIMER_TIMG_NUM_INPUT2_INTR_EN_1_qei_ctr_dc_en_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_EN_1_qei_ctr_dc_en_MASK) + ((qei_err_en<<TIMER_TIMG_NUM_INPUT2_INTR_EN_1_qei_err_en_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_EN_1_qei_err_en_MASK);
}

static inline void TIMER_TIMG_NUM_INPUT2_INTR_NMI_EN_0_WRITE(TIMER_TIMG_NUM_INPUT2_REGS_s * registers, uint32_t ctr_zero_nmi_en, uint32_t ctr_load_nmi_en, uint32_t ccd_0_nmi_en, uint32_t ccu_0_nmi_en, uint32_t ccd_1_nmi_en, uint32_t ccu_1_nmi_en, uint32_t ccd_2_nmi_en, uint32_t ccu_2_nmi_en, uint32_t ccd_3_nmi_en, uint32_t ccu_3_nmi_en, uint32_t ccd_4_nmi_en, uint32_t ccu_4_nmi_en, uint32_t ccd_5_nmi_en, uint32_t ccu_5_nmi_en, uint32_t fault_nmi_en, uint32_t trig_ov_nmi_en) {
    registers->INTR_NMI_EN_0.packed_w =  + ((ctr_zero_nmi_en<<TIMER_TIMG_NUM_INPUT2_INTR_NMI_EN_0_ctr_zero_nmi_en_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_NMI_EN_0_ctr_zero_nmi_en_MASK) + ((ctr_load_nmi_en<<TIMER_TIMG_NUM_INPUT2_INTR_NMI_EN_0_ctr_load_nmi_en_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_NMI_EN_0_ctr_load_nmi_en_MASK) + ((ccd_0_nmi_en<<TIMER_TIMG_NUM_INPUT2_INTR_NMI_EN_0_ccd_0_nmi_en_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_NMI_EN_0_ccd_0_nmi_en_MASK) + ((ccu_0_nmi_en<<TIMER_TIMG_NUM_INPUT2_INTR_NMI_EN_0_ccu_0_nmi_en_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_NMI_EN_0_ccu_0_nmi_en_MASK) + ((ccd_1_nmi_en<<TIMER_TIMG_NUM_INPUT2_INTR_NMI_EN_0_ccd_1_nmi_en_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_NMI_EN_0_ccd_1_nmi_en_MASK) + ((ccu_1_nmi_en<<TIMER_TIMG_NUM_INPUT2_INTR_NMI_EN_0_ccu_1_nmi_en_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_NMI_EN_0_ccu_1_nmi_en_MASK) + ((ccd_2_nmi_en<<TIMER_TIMG_NUM_INPUT2_INTR_NMI_EN_0_ccd_2_nmi_en_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_NMI_EN_0_ccd_2_nmi_en_MASK) + ((ccu_2_nmi_en<<TIMER_TIMG_NUM_INPUT2_INTR_NMI_EN_0_ccu_2_nmi_en_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_NMI_EN_0_ccu_2_nmi_en_MASK) + ((ccd_3_nmi_en<<TIMER_TIMG_NUM_INPUT2_INTR_NMI_EN_0_ccd_3_nmi_en_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_NMI_EN_0_ccd_3_nmi_en_MASK) + ((ccu_3_nmi_en<<TIMER_TIMG_NUM_INPUT2_INTR_NMI_EN_0_ccu_3_nmi_en_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_NMI_EN_0_ccu_3_nmi_en_MASK) + ((ccd_4_nmi_en<<TIMER_TIMG_NUM_INPUT2_INTR_NMI_EN_0_ccd_4_nmi_en_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_NMI_EN_0_ccd_4_nmi_en_MASK) + ((ccu_4_nmi_en<<TIMER_TIMG_NUM_INPUT2_INTR_NMI_EN_0_ccu_4_nmi_en_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_NMI_EN_0_ccu_4_nmi_en_MASK) + ((ccd_5_nmi_en<<TIMER_TIMG_NUM_INPUT2_INTR_NMI_EN_0_ccd_5_nmi_en_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_NMI_EN_0_ccd_5_nmi_en_MASK) + ((ccu_5_nmi_en<<TIMER_TIMG_NUM_INPUT2_INTR_NMI_EN_0_ccu_5_nmi_en_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_NMI_EN_0_ccu_5_nmi_en_MASK) + ((fault_nmi_en<<TIMER_TIMG_NUM_INPUT2_INTR_NMI_EN_0_fault_nmi_en_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_NMI_EN_0_fault_nmi_en_MASK) + ((trig_ov_nmi_en<<TIMER_TIMG_NUM_INPUT2_INTR_NMI_EN_0_trig_ov_nmi_en_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_NMI_EN_0_trig_ov_nmi_en_MASK);
}

static inline void TIMER_TIMG_NUM_INPUT2_INTR_NMI_EN_1_WRITE(TIMER_TIMG_NUM_INPUT2_REGS_s * registers, uint32_t rctr_zero_nmi_en, uint32_t qei_ctr_dc_nmi_en, uint32_t qei_err_nmi_en) {
    registers->INTR_NMI_EN_1.packed_w =  + ((rctr_zero_nmi_en<<TIMER_TIMG_NUM_INPUT2_INTR_NMI_EN_1_rctr_zero_nmi_en_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_NMI_EN_1_rctr_zero_nmi_en_MASK) + ((qei_ctr_dc_nmi_en<<TIMER_TIMG_NUM_INPUT2_INTR_NMI_EN_1_qei_ctr_dc_nmi_en_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_NMI_EN_1_qei_ctr_dc_nmi_en_MASK) + ((qei_err_nmi_en<<TIMER_TIMG_NUM_INPUT2_INTR_NMI_EN_1_qei_err_nmi_en_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_NMI_EN_1_qei_err_nmi_en_MASK);
}

static inline void TIMER_TIMG_NUM_INPUT2_EVENT_EN_0_0_WRITE(TIMER_TIMG_NUM_INPUT2_REGS_s * registers, uint32_t ctr_zero_event_en_0, uint32_t ctr_load_event_en_0, uint32_t ccd_0_event_en_0, uint32_t ccu_0_event_en_0, uint32_t ccd_1_event_en_0, uint32_t ccu_1_event_en_0, uint32_t ccd_2_event_en_0, uint32_t ccu_2_event_en_0, uint32_t ccd_3_event_en_0, uint32_t ccu_3_event_en_0, uint32_t ccd_4_event_en_0, uint32_t ccu_4_event_en_0, uint32_t ccd_5_event_en_0, uint32_t ccu_5_event_en_0, uint32_t fault_event_en_0, uint32_t trig_ov_event_en_0) {
    registers->EVENT_EN_0_0.packed_w =  + ((ctr_zero_event_en_0<<TIMER_TIMG_NUM_INPUT2_EVENT_EN_0_0_ctr_zero_event_en_0_OFS)&TIMER_TIMG_NUM_INPUT2_EVENT_EN_0_0_ctr_zero_event_en_0_MASK) + ((ctr_load_event_en_0<<TIMER_TIMG_NUM_INPUT2_EVENT_EN_0_0_ctr_load_event_en_0_OFS)&TIMER_TIMG_NUM_INPUT2_EVENT_EN_0_0_ctr_load_event_en_0_MASK) + ((ccd_0_event_en_0<<TIMER_TIMG_NUM_INPUT2_EVENT_EN_0_0_ccd_0_event_en_0_OFS)&TIMER_TIMG_NUM_INPUT2_EVENT_EN_0_0_ccd_0_event_en_0_MASK) + ((ccu_0_event_en_0<<TIMER_TIMG_NUM_INPUT2_EVENT_EN_0_0_ccu_0_event_en_0_OFS)&TIMER_TIMG_NUM_INPUT2_EVENT_EN_0_0_ccu_0_event_en_0_MASK) + ((ccd_1_event_en_0<<TIMER_TIMG_NUM_INPUT2_EVENT_EN_0_0_ccd_1_event_en_0_OFS)&TIMER_TIMG_NUM_INPUT2_EVENT_EN_0_0_ccd_1_event_en_0_MASK) + ((ccu_1_event_en_0<<TIMER_TIMG_NUM_INPUT2_EVENT_EN_0_0_ccu_1_event_en_0_OFS)&TIMER_TIMG_NUM_INPUT2_EVENT_EN_0_0_ccu_1_event_en_0_MASK) + ((ccd_2_event_en_0<<TIMER_TIMG_NUM_INPUT2_EVENT_EN_0_0_ccd_2_event_en_0_OFS)&TIMER_TIMG_NUM_INPUT2_EVENT_EN_0_0_ccd_2_event_en_0_MASK) + ((ccu_2_event_en_0<<TIMER_TIMG_NUM_INPUT2_EVENT_EN_0_0_ccu_2_event_en_0_OFS)&TIMER_TIMG_NUM_INPUT2_EVENT_EN_0_0_ccu_2_event_en_0_MASK) + ((ccd_3_event_en_0<<TIMER_TIMG_NUM_INPUT2_EVENT_EN_0_0_ccd_3_event_en_0_OFS)&TIMER_TIMG_NUM_INPUT2_EVENT_EN_0_0_ccd_3_event_en_0_MASK) + ((ccu_3_event_en_0<<TIMER_TIMG_NUM_INPUT2_EVENT_EN_0_0_ccu_3_event_en_0_OFS)&TIMER_TIMG_NUM_INPUT2_EVENT_EN_0_0_ccu_3_event_en_0_MASK) + ((ccd_4_event_en_0<<TIMER_TIMG_NUM_INPUT2_EVENT_EN_0_0_ccd_4_event_en_0_OFS)&TIMER_TIMG_NUM_INPUT2_EVENT_EN_0_0_ccd_4_event_en_0_MASK) + ((ccu_4_event_en_0<<TIMER_TIMG_NUM_INPUT2_EVENT_EN_0_0_ccu_4_event_en_0_OFS)&TIMER_TIMG_NUM_INPUT2_EVENT_EN_0_0_ccu_4_event_en_0_MASK) + ((ccd_5_event_en_0<<TIMER_TIMG_NUM_INPUT2_EVENT_EN_0_0_ccd_5_event_en_0_OFS)&TIMER_TIMG_NUM_INPUT2_EVENT_EN_0_0_ccd_5_event_en_0_MASK) + ((ccu_5_event_en_0<<TIMER_TIMG_NUM_INPUT2_EVENT_EN_0_0_ccu_5_event_en_0_OFS)&TIMER_TIMG_NUM_INPUT2_EVENT_EN_0_0_ccu_5_event_en_0_MASK) + ((fault_event_en_0<<TIMER_TIMG_NUM_INPUT2_EVENT_EN_0_0_fault_event_en_0_OFS)&TIMER_TIMG_NUM_INPUT2_EVENT_EN_0_0_fault_event_en_0_MASK) + ((trig_ov_event_en_0<<TIMER_TIMG_NUM_INPUT2_EVENT_EN_0_0_trig_ov_event_en_0_OFS)&TIMER_TIMG_NUM_INPUT2_EVENT_EN_0_0_trig_ov_event_en_0_MASK);
}

static inline void TIMER_TIMG_NUM_INPUT2_EVENT_EN_0_1_WRITE(TIMER_TIMG_NUM_INPUT2_REGS_s * registers, uint32_t rctr_zero_event_en_0, uint32_t qei_ctr_dc_event_en_0, uint32_t qei_err_event_en_0) {
    registers->EVENT_EN_0_1.packed_w =  + ((rctr_zero_event_en_0<<TIMER_TIMG_NUM_INPUT2_EVENT_EN_0_1_rctr_zero_event_en_0_OFS)&TIMER_TIMG_NUM_INPUT2_EVENT_EN_0_1_rctr_zero_event_en_0_MASK) + ((qei_ctr_dc_event_en_0<<TIMER_TIMG_NUM_INPUT2_EVENT_EN_0_1_qei_ctr_dc_event_en_0_OFS)&TIMER_TIMG_NUM_INPUT2_EVENT_EN_0_1_qei_ctr_dc_event_en_0_MASK) + ((qei_err_event_en_0<<TIMER_TIMG_NUM_INPUT2_EVENT_EN_0_1_qei_err_event_en_0_OFS)&TIMER_TIMG_NUM_INPUT2_EVENT_EN_0_1_qei_err_event_en_0_MASK);
}

static inline void TIMER_TIMG_NUM_INPUT2_EVENT_EN_1_0_WRITE(TIMER_TIMG_NUM_INPUT2_REGS_s * registers, uint32_t ctr_zero_event_en_1, uint32_t ctr_load_event_en_1, uint32_t ccd_0_event_en_1, uint32_t ccu_0_event_en_1, uint32_t ccd_1_event_en_1, uint32_t ccu_1_event_en_1, uint32_t ccd_2_event_en_1, uint32_t ccu_2_event_en_1, uint32_t ccd_3_event_en_1, uint32_t ccu_3_event_en_1, uint32_t ccd_4_event_en_1, uint32_t ccu_4_event_en_1, uint32_t ccd_5_event_en_1, uint32_t ccu_5_event_en_1, uint32_t fault_event_en_1, uint32_t trig_ov_event_en_1) {
    registers->EVENT_EN_1_0.packed_w =  + ((ctr_zero_event_en_1<<TIMER_TIMG_NUM_INPUT2_EVENT_EN_1_0_ctr_zero_event_en_1_OFS)&TIMER_TIMG_NUM_INPUT2_EVENT_EN_1_0_ctr_zero_event_en_1_MASK) + ((ctr_load_event_en_1<<TIMER_TIMG_NUM_INPUT2_EVENT_EN_1_0_ctr_load_event_en_1_OFS)&TIMER_TIMG_NUM_INPUT2_EVENT_EN_1_0_ctr_load_event_en_1_MASK) + ((ccd_0_event_en_1<<TIMER_TIMG_NUM_INPUT2_EVENT_EN_1_0_ccd_0_event_en_1_OFS)&TIMER_TIMG_NUM_INPUT2_EVENT_EN_1_0_ccd_0_event_en_1_MASK) + ((ccu_0_event_en_1<<TIMER_TIMG_NUM_INPUT2_EVENT_EN_1_0_ccu_0_event_en_1_OFS)&TIMER_TIMG_NUM_INPUT2_EVENT_EN_1_0_ccu_0_event_en_1_MASK) + ((ccd_1_event_en_1<<TIMER_TIMG_NUM_INPUT2_EVENT_EN_1_0_ccd_1_event_en_1_OFS)&TIMER_TIMG_NUM_INPUT2_EVENT_EN_1_0_ccd_1_event_en_1_MASK) + ((ccu_1_event_en_1<<TIMER_TIMG_NUM_INPUT2_EVENT_EN_1_0_ccu_1_event_en_1_OFS)&TIMER_TIMG_NUM_INPUT2_EVENT_EN_1_0_ccu_1_event_en_1_MASK) + ((ccd_2_event_en_1<<TIMER_TIMG_NUM_INPUT2_EVENT_EN_1_0_ccd_2_event_en_1_OFS)&TIMER_TIMG_NUM_INPUT2_EVENT_EN_1_0_ccd_2_event_en_1_MASK) + ((ccu_2_event_en_1<<TIMER_TIMG_NUM_INPUT2_EVENT_EN_1_0_ccu_2_event_en_1_OFS)&TIMER_TIMG_NUM_INPUT2_EVENT_EN_1_0_ccu_2_event_en_1_MASK) + ((ccd_3_event_en_1<<TIMER_TIMG_NUM_INPUT2_EVENT_EN_1_0_ccd_3_event_en_1_OFS)&TIMER_TIMG_NUM_INPUT2_EVENT_EN_1_0_ccd_3_event_en_1_MASK) + ((ccu_3_event_en_1<<TIMER_TIMG_NUM_INPUT2_EVENT_EN_1_0_ccu_3_event_en_1_OFS)&TIMER_TIMG_NUM_INPUT2_EVENT_EN_1_0_ccu_3_event_en_1_MASK) + ((ccd_4_event_en_1<<TIMER_TIMG_NUM_INPUT2_EVENT_EN_1_0_ccd_4_event_en_1_OFS)&TIMER_TIMG_NUM_INPUT2_EVENT_EN_1_0_ccd_4_event_en_1_MASK) + ((ccu_4_event_en_1<<TIMER_TIMG_NUM_INPUT2_EVENT_EN_1_0_ccu_4_event_en_1_OFS)&TIMER_TIMG_NUM_INPUT2_EVENT_EN_1_0_ccu_4_event_en_1_MASK) + ((ccd_5_event_en_1<<TIMER_TIMG_NUM_INPUT2_EVENT_EN_1_0_ccd_5_event_en_1_OFS)&TIMER_TIMG_NUM_INPUT2_EVENT_EN_1_0_ccd_5_event_en_1_MASK) + ((ccu_5_event_en_1<<TIMER_TIMG_NUM_INPUT2_EVENT_EN_1_0_ccu_5_event_en_1_OFS)&TIMER_TIMG_NUM_INPUT2_EVENT_EN_1_0_ccu_5_event_en_1_MASK) + ((fault_event_en_1<<TIMER_TIMG_NUM_INPUT2_EVENT_EN_1_0_fault_event_en_1_OFS)&TIMER_TIMG_NUM_INPUT2_EVENT_EN_1_0_fault_event_en_1_MASK) + ((trig_ov_event_en_1<<TIMER_TIMG_NUM_INPUT2_EVENT_EN_1_0_trig_ov_event_en_1_OFS)&TIMER_TIMG_NUM_INPUT2_EVENT_EN_1_0_trig_ov_event_en_1_MASK);
}

static inline void TIMER_TIMG_NUM_INPUT2_EVENT_EN_1_1_WRITE(TIMER_TIMG_NUM_INPUT2_REGS_s * registers, uint32_t rctr_zero_event_en_1, uint32_t qei_ctr_dc_event_en_1, uint32_t qei_err_event_en_1) {
    registers->EVENT_EN_1_1.packed_w =  + ((rctr_zero_event_en_1<<TIMER_TIMG_NUM_INPUT2_EVENT_EN_1_1_rctr_zero_event_en_1_OFS)&TIMER_TIMG_NUM_INPUT2_EVENT_EN_1_1_rctr_zero_event_en_1_MASK) + ((qei_ctr_dc_event_en_1<<TIMER_TIMG_NUM_INPUT2_EVENT_EN_1_1_qei_ctr_dc_event_en_1_OFS)&TIMER_TIMG_NUM_INPUT2_EVENT_EN_1_1_qei_ctr_dc_event_en_1_MASK) + ((qei_err_event_en_1<<TIMER_TIMG_NUM_INPUT2_EVENT_EN_1_1_qei_err_event_en_1_OFS)&TIMER_TIMG_NUM_INPUT2_EVENT_EN_1_1_qei_err_event_en_1_MASK);
}

static inline void TIMER_TIMG_NUM_INPUT2_INTR_SW_SET_WRITE(TIMER_TIMG_NUM_INPUT2_REGS_s * registers, uint32_t ctr_zero_sw_set, uint32_t ctr_load_sw_set, uint32_t ccd_0_sw_set, uint32_t ccu_0_sw_set, uint32_t ccd_1_sw_set, uint32_t ccu_1_sw_set, uint32_t ccd_2_sw_set, uint32_t ccu_2_sw_set, uint32_t ccd_3_sw_set, uint32_t ccu_3_sw_set, uint32_t ccd_4_sw_set, uint32_t ccu_4_sw_set, uint32_t ccd_5_sw_set, uint32_t ccu_5_sw_set, uint32_t fault_sw_set, uint32_t trig_ov_sw_set, uint32_t rctr_zero_sw_set, uint32_t qei_ctr_dc_sw_set, uint32_t qei_err_sw_set) {
    registers->INTR_SW_SET.packed_w =  + ((ctr_zero_sw_set<<TIMER_TIMG_NUM_INPUT2_INTR_SW_SET_ctr_zero_sw_set_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_SW_SET_ctr_zero_sw_set_MASK) + ((ctr_load_sw_set<<TIMER_TIMG_NUM_INPUT2_INTR_SW_SET_ctr_load_sw_set_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_SW_SET_ctr_load_sw_set_MASK) + ((ccd_0_sw_set<<TIMER_TIMG_NUM_INPUT2_INTR_SW_SET_ccd_0_sw_set_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_SW_SET_ccd_0_sw_set_MASK) + ((ccu_0_sw_set<<TIMER_TIMG_NUM_INPUT2_INTR_SW_SET_ccu_0_sw_set_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_SW_SET_ccu_0_sw_set_MASK) + ((ccd_1_sw_set<<TIMER_TIMG_NUM_INPUT2_INTR_SW_SET_ccd_1_sw_set_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_SW_SET_ccd_1_sw_set_MASK) + ((ccu_1_sw_set<<TIMER_TIMG_NUM_INPUT2_INTR_SW_SET_ccu_1_sw_set_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_SW_SET_ccu_1_sw_set_MASK) + ((ccd_2_sw_set<<TIMER_TIMG_NUM_INPUT2_INTR_SW_SET_ccd_2_sw_set_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_SW_SET_ccd_2_sw_set_MASK) + ((ccu_2_sw_set<<TIMER_TIMG_NUM_INPUT2_INTR_SW_SET_ccu_2_sw_set_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_SW_SET_ccu_2_sw_set_MASK) + ((ccd_3_sw_set<<TIMER_TIMG_NUM_INPUT2_INTR_SW_SET_ccd_3_sw_set_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_SW_SET_ccd_3_sw_set_MASK) + ((ccu_3_sw_set<<TIMER_TIMG_NUM_INPUT2_INTR_SW_SET_ccu_3_sw_set_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_SW_SET_ccu_3_sw_set_MASK) + ((ccd_4_sw_set<<TIMER_TIMG_NUM_INPUT2_INTR_SW_SET_ccd_4_sw_set_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_SW_SET_ccd_4_sw_set_MASK) + ((ccu_4_sw_set<<TIMER_TIMG_NUM_INPUT2_INTR_SW_SET_ccu_4_sw_set_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_SW_SET_ccu_4_sw_set_MASK) + ((ccd_5_sw_set<<TIMER_TIMG_NUM_INPUT2_INTR_SW_SET_ccd_5_sw_set_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_SW_SET_ccd_5_sw_set_MASK) + ((ccu_5_sw_set<<TIMER_TIMG_NUM_INPUT2_INTR_SW_SET_ccu_5_sw_set_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_SW_SET_ccu_5_sw_set_MASK) + ((fault_sw_set<<TIMER_TIMG_NUM_INPUT2_INTR_SW_SET_fault_sw_set_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_SW_SET_fault_sw_set_MASK) + ((trig_ov_sw_set<<TIMER_TIMG_NUM_INPUT2_INTR_SW_SET_trig_ov_sw_set_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_SW_SET_trig_ov_sw_set_MASK) + ((rctr_zero_sw_set<<TIMER_TIMG_NUM_INPUT2_INTR_SW_SET_rctr_zero_sw_set_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_SW_SET_rctr_zero_sw_set_MASK) + ((qei_ctr_dc_sw_set<<TIMER_TIMG_NUM_INPUT2_INTR_SW_SET_qei_ctr_dc_sw_set_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_SW_SET_qei_ctr_dc_sw_set_MASK) + ((qei_err_sw_set<<TIMER_TIMG_NUM_INPUT2_INTR_SW_SET_qei_err_sw_set_OFS)&TIMER_TIMG_NUM_INPUT2_INTR_SW_SET_qei_err_sw_set_MASK);
}

static inline void TIMER_TIMG_NUM_INPUT2_CLK_CONFIG_WRITE(TIMER_TIMG_NUM_INPUT2_REGS_s * registers, uint32_t clk_sel, uint32_t clk_div) {
    registers->CLK_CONFIG.packed_w =  + ((clk_sel<<TIMER_TIMG_NUM_INPUT2_CLK_CONFIG_clk_sel_OFS)&TIMER_TIMG_NUM_INPUT2_CLK_CONFIG_clk_sel_MASK) + ((clk_div<<TIMER_TIMG_NUM_INPUT2_CLK_CONFIG_clk_div_OFS)&TIMER_TIMG_NUM_INPUT2_CLK_CONFIG_clk_div_MASK);
}

static inline void TIMER_TIMG_NUM_INPUT2_TRIG_IN_WRITE(TIMER_TIMG_NUM_INPUT2_REGS_s * registers, uint32_t trig_en, uint32_t trig_sel) {
    registers->TRIG_IN.packed_w =  + ((trig_en<<TIMER_TIMG_NUM_INPUT2_TRIG_IN_trig_en_OFS)&TIMER_TIMG_NUM_INPUT2_TRIG_IN_trig_en_MASK) + ((trig_sel<<TIMER_TIMG_NUM_INPUT2_TRIG_IN_trig_sel_OFS)&TIMER_TIMG_NUM_INPUT2_TRIG_IN_trig_sel_MASK);
}

static inline void TIMER_TIMG_NUM_INPUT2_TRIG_OUT_WRITE(TIMER_TIMG_NUM_INPUT2_REGS_s * registers, uint32_t trig_out_en, uint32_t trig_sw_en, uint32_t trig_hw_en, uint32_t trig_hw_sel) {
    registers->TRIG_OUT.packed_w =  + ((trig_out_en<<TIMER_TIMG_NUM_INPUT2_TRIG_OUT_trig_out_en_OFS)&TIMER_TIMG_NUM_INPUT2_TRIG_OUT_trig_out_en_MASK) + ((trig_sw_en<<TIMER_TIMG_NUM_INPUT2_TRIG_OUT_trig_sw_en_OFS)&TIMER_TIMG_NUM_INPUT2_TRIG_OUT_trig_sw_en_MASK) + ((trig_hw_en<<TIMER_TIMG_NUM_INPUT2_TRIG_OUT_trig_hw_en_OFS)&TIMER_TIMG_NUM_INPUT2_TRIG_OUT_trig_hw_en_MASK) + ((trig_hw_sel<<TIMER_TIMG_NUM_INPUT2_TRIG_OUT_trig_hw_sel_OFS)&TIMER_TIMG_NUM_INPUT2_TRIG_OUT_trig_hw_sel_MASK);
}

static inline void TIMER_TIMG_NUM_INPUT2_INPUT_FILTER_CC_0_WRITE(TIMER_TIMG_NUM_INPUT2_REGS_s * registers, uint32_t filter_en_0, uint32_t is_consecutive_prd_0, uint32_t filter_period_0) {
    registers->INPUT_FILTER_CC_0.packed_w =  + ((filter_en_0<<TIMER_TIMG_NUM_INPUT2_INPUT_FILTER_CC_0_filter_en_0_OFS)&TIMER_TIMG_NUM_INPUT2_INPUT_FILTER_CC_0_filter_en_0_MASK) + ((is_consecutive_prd_0<<TIMER_TIMG_NUM_INPUT2_INPUT_FILTER_CC_0_is_consecutive_prd_0_OFS)&TIMER_TIMG_NUM_INPUT2_INPUT_FILTER_CC_0_is_consecutive_prd_0_MASK) + ((filter_period_0<<TIMER_TIMG_NUM_INPUT2_INPUT_FILTER_CC_0_filter_period_0_OFS)&TIMER_TIMG_NUM_INPUT2_INPUT_FILTER_CC_0_filter_period_0_MASK);
}

static inline void TIMER_TIMG_NUM_INPUT2_INPUT_FILTER_CC_1_WRITE(TIMER_TIMG_NUM_INPUT2_REGS_s * registers, uint32_t filter_en_1, uint32_t is_consecutive_prd_1, uint32_t filter_period_1) {
    registers->INPUT_FILTER_CC_1.packed_w =  + ((filter_en_1<<TIMER_TIMG_NUM_INPUT2_INPUT_FILTER_CC_1_filter_en_1_OFS)&TIMER_TIMG_NUM_INPUT2_INPUT_FILTER_CC_1_filter_en_1_MASK) + ((is_consecutive_prd_1<<TIMER_TIMG_NUM_INPUT2_INPUT_FILTER_CC_1_is_consecutive_prd_1_OFS)&TIMER_TIMG_NUM_INPUT2_INPUT_FILTER_CC_1_is_consecutive_prd_1_MASK) + ((filter_period_1<<TIMER_TIMG_NUM_INPUT2_INPUT_FILTER_CC_1_filter_period_1_OFS)&TIMER_TIMG_NUM_INPUT2_INPUT_FILTER_CC_1_filter_period_1_MASK);
}

static inline void TIMER_TIMG_NUM_INPUT2_INPUT_CC_0_WRITE(TIMER_TIMG_NUM_INPUT2_REGS_s * registers, uint32_t input_sel_0, uint32_t input_inv_0) {
    registers->INPUT_CC_0.packed_w =  + ((input_sel_0<<TIMER_TIMG_NUM_INPUT2_INPUT_CC_0_input_sel_0_OFS)&TIMER_TIMG_NUM_INPUT2_INPUT_CC_0_input_sel_0_MASK) + ((input_inv_0<<TIMER_TIMG_NUM_INPUT2_INPUT_CC_0_input_inv_0_OFS)&TIMER_TIMG_NUM_INPUT2_INPUT_CC_0_input_inv_0_MASK);
}

static inline void TIMER_TIMG_NUM_INPUT2_INPUT_CC_1_WRITE(TIMER_TIMG_NUM_INPUT2_REGS_s * registers, uint32_t input_sel_1, uint32_t input_inv_1) {
    registers->INPUT_CC_1.packed_w =  + ((input_sel_1<<TIMER_TIMG_NUM_INPUT2_INPUT_CC_1_input_sel_1_OFS)&TIMER_TIMG_NUM_INPUT2_INPUT_CC_1_input_sel_1_MASK) + ((input_inv_1<<TIMER_TIMG_NUM_INPUT2_INPUT_CC_1_input_inv_1_OFS)&TIMER_TIMG_NUM_INPUT2_INPUT_CC_1_input_inv_1_MASK);
}

static inline void TIMER_TIMG_NUM_INPUT2_CC0_CMN_CTRL_WRITE(TIMER_TIMG_NUM_INPUT2_REGS_s * registers, uint32_t is_capture_0, uint32_t cc2d_sel_0, uint32_t cc2u_sel_0, uint32_t suppress_coc_event_gen_0) {
    registers->CC0_CMN_CTRL.packed_w =  + ((is_capture_0<<TIMER_TIMG_NUM_INPUT2_CC0_CMN_CTRL_is_capture_0_OFS)&TIMER_TIMG_NUM_INPUT2_CC0_CMN_CTRL_is_capture_0_MASK) + ((cc2d_sel_0<<TIMER_TIMG_NUM_INPUT2_CC0_CMN_CTRL_cc2d_sel_0_OFS)&TIMER_TIMG_NUM_INPUT2_CC0_CMN_CTRL_cc2d_sel_0_MASK) + ((cc2u_sel_0<<TIMER_TIMG_NUM_INPUT2_CC0_CMN_CTRL_cc2u_sel_0_OFS)&TIMER_TIMG_NUM_INPUT2_CC0_CMN_CTRL_cc2u_sel_0_MASK) + ((suppress_coc_event_gen_0<<TIMER_TIMG_NUM_INPUT2_CC0_CMN_CTRL_suppress_coc_event_gen_0_OFS)&TIMER_TIMG_NUM_INPUT2_CC0_CMN_CTRL_suppress_coc_event_gen_0_MASK);
}

static inline void TIMER_TIMG_NUM_INPUT2_CC1_CMN_CTRL_WRITE(TIMER_TIMG_NUM_INPUT2_REGS_s * registers, uint32_t is_capture_1, uint32_t cc2d_sel_1, uint32_t cc2u_sel_1, uint32_t suppress_coc_event_gen_1) {
    registers->CC1_CMN_CTRL.packed_w =  + ((is_capture_1<<TIMER_TIMG_NUM_INPUT2_CC1_CMN_CTRL_is_capture_1_OFS)&TIMER_TIMG_NUM_INPUT2_CC1_CMN_CTRL_is_capture_1_MASK) + ((cc2d_sel_1<<TIMER_TIMG_NUM_INPUT2_CC1_CMN_CTRL_cc2d_sel_1_OFS)&TIMER_TIMG_NUM_INPUT2_CC1_CMN_CTRL_cc2d_sel_1_MASK) + ((cc2u_sel_1<<TIMER_TIMG_NUM_INPUT2_CC1_CMN_CTRL_cc2u_sel_1_OFS)&TIMER_TIMG_NUM_INPUT2_CC1_CMN_CTRL_cc2u_sel_1_MASK) + ((suppress_coc_event_gen_1<<TIMER_TIMG_NUM_INPUT2_CC1_CMN_CTRL_suppress_coc_event_gen_1_OFS)&TIMER_TIMG_NUM_INPUT2_CC1_CMN_CTRL_suppress_coc_event_gen_1_MASK);
}

static inline void TIMER_TIMG_NUM_INPUT2_CC0_CAPTURE_CTRL_WRITE(TIMER_TIMG_NUM_INPUT2_REGS_s * registers, uint32_t cap_cond_0, uint32_t load_cond_0, uint32_t zero_cond_0, uint32_t adv_cond_0, uint32_t cap_val_0) {
    registers->CC0_CAPTURE_CTRL.packed_w =  + ((cap_cond_0<<TIMER_TIMG_NUM_INPUT2_CC0_CAPTURE_CTRL_cap_cond_0_OFS)&TIMER_TIMG_NUM_INPUT2_CC0_CAPTURE_CTRL_cap_cond_0_MASK) + ((load_cond_0<<TIMER_TIMG_NUM_INPUT2_CC0_CAPTURE_CTRL_load_cond_0_OFS)&TIMER_TIMG_NUM_INPUT2_CC0_CAPTURE_CTRL_load_cond_0_MASK) + ((zero_cond_0<<TIMER_TIMG_NUM_INPUT2_CC0_CAPTURE_CTRL_zero_cond_0_OFS)&TIMER_TIMG_NUM_INPUT2_CC0_CAPTURE_CTRL_zero_cond_0_MASK) + ((adv_cond_0<<TIMER_TIMG_NUM_INPUT2_CC0_CAPTURE_CTRL_adv_cond_0_OFS)&TIMER_TIMG_NUM_INPUT2_CC0_CAPTURE_CTRL_adv_cond_0_MASK) + ((cap_val_0<<TIMER_TIMG_NUM_INPUT2_CC0_CAPTURE_CTRL_cap_val_0_OFS)&TIMER_TIMG_NUM_INPUT2_CC0_CAPTURE_CTRL_cap_val_0_MASK);
}

static inline void TIMER_TIMG_NUM_INPUT2_CC1_CAPTURE_CTRL_WRITE(TIMER_TIMG_NUM_INPUT2_REGS_s * registers, uint32_t cap_cond_1, uint32_t load_cond_1, uint32_t zero_cond_1, uint32_t adv_cond_1, uint32_t cap_val_1) {
    registers->CC1_CAPTURE_CTRL.packed_w =  + ((cap_cond_1<<TIMER_TIMG_NUM_INPUT2_CC1_CAPTURE_CTRL_cap_cond_1_OFS)&TIMER_TIMG_NUM_INPUT2_CC1_CAPTURE_CTRL_cap_cond_1_MASK) + ((load_cond_1<<TIMER_TIMG_NUM_INPUT2_CC1_CAPTURE_CTRL_load_cond_1_OFS)&TIMER_TIMG_NUM_INPUT2_CC1_CAPTURE_CTRL_load_cond_1_MASK) + ((zero_cond_1<<TIMER_TIMG_NUM_INPUT2_CC1_CAPTURE_CTRL_zero_cond_1_OFS)&TIMER_TIMG_NUM_INPUT2_CC1_CAPTURE_CTRL_zero_cond_1_MASK) + ((adv_cond_1<<TIMER_TIMG_NUM_INPUT2_CC1_CAPTURE_CTRL_adv_cond_1_OFS)&TIMER_TIMG_NUM_INPUT2_CC1_CAPTURE_CTRL_adv_cond_1_MASK) + ((cap_val_1<<TIMER_TIMG_NUM_INPUT2_CC1_CAPTURE_CTRL_cap_val_1_OFS)&TIMER_TIMG_NUM_INPUT2_CC1_CAPTURE_CTRL_cap_val_1_MASK);
}

static inline void TIMER_TIMG_NUM_INPUT2_CC0_COMPARE_CTRL_WRITE(TIMER_TIMG_NUM_INPUT2_REGS_s * registers, uint32_t comp_val_0, uint32_t comp_val_update_method_0, uint32_t ccact_update_method_0) {
    registers->CC0_COMPARE_CTRL.packed_w =  + ((comp_val_0<<TIMER_TIMG_NUM_INPUT2_CC0_COMPARE_CTRL_comp_val_0_OFS)&TIMER_TIMG_NUM_INPUT2_CC0_COMPARE_CTRL_comp_val_0_MASK) + ((comp_val_update_method_0<<TIMER_TIMG_NUM_INPUT2_CC0_COMPARE_CTRL_comp_val_update_method_0_OFS)&TIMER_TIMG_NUM_INPUT2_CC0_COMPARE_CTRL_comp_val_update_method_0_MASK) + ((ccact_update_method_0<<TIMER_TIMG_NUM_INPUT2_CC0_COMPARE_CTRL_ccact_update_method_0_OFS)&TIMER_TIMG_NUM_INPUT2_CC0_COMPARE_CTRL_ccact_update_method_0_MASK);
}

static inline void TIMER_TIMG_NUM_INPUT2_CC1_COMPARE_CTRL_WRITE(TIMER_TIMG_NUM_INPUT2_REGS_s * registers, uint32_t comp_val_1, uint32_t comp_val_update_method_1, uint32_t ccact_update_method_1) {
    registers->CC1_COMPARE_CTRL.packed_w =  + ((comp_val_1<<TIMER_TIMG_NUM_INPUT2_CC1_COMPARE_CTRL_comp_val_1_OFS)&TIMER_TIMG_NUM_INPUT2_CC1_COMPARE_CTRL_comp_val_1_MASK) + ((comp_val_update_method_1<<TIMER_TIMG_NUM_INPUT2_CC1_COMPARE_CTRL_comp_val_update_method_1_OFS)&TIMER_TIMG_NUM_INPUT2_CC1_COMPARE_CTRL_comp_val_update_method_1_MASK) + ((ccact_update_method_1<<TIMER_TIMG_NUM_INPUT2_CC1_COMPARE_CTRL_ccact_update_method_1_OFS)&TIMER_TIMG_NUM_INPUT2_CC1_COMPARE_CTRL_ccact_update_method_1_MASK);
}

static inline void TIMER_TIMG_NUM_INPUT2_CC0_CC_PWM_CFG_WRITE(TIMER_TIMG_NUM_INPUT2_REGS_s * registers, uint32_t cc_out_cc2d_0, uint32_t cc_out_cc2u_0, uint32_t cc_out_ccd_0, uint32_t cc_out_ccu_0, uint32_t cc_out_load_0, uint32_t cc_out_zero_0) {
    registers->CC0_CC_PWM_CFG.packed_w =  + ((cc_out_cc2d_0<<TIMER_TIMG_NUM_INPUT2_CC0_CC_PWM_CFG_cc_out_cc2d_0_OFS)&TIMER_TIMG_NUM_INPUT2_CC0_CC_PWM_CFG_cc_out_cc2d_0_MASK) + ((cc_out_cc2u_0<<TIMER_TIMG_NUM_INPUT2_CC0_CC_PWM_CFG_cc_out_cc2u_0_OFS)&TIMER_TIMG_NUM_INPUT2_CC0_CC_PWM_CFG_cc_out_cc2u_0_MASK) + ((cc_out_ccd_0<<TIMER_TIMG_NUM_INPUT2_CC0_CC_PWM_CFG_cc_out_ccd_0_OFS)&TIMER_TIMG_NUM_INPUT2_CC0_CC_PWM_CFG_cc_out_ccd_0_MASK) + ((cc_out_ccu_0<<TIMER_TIMG_NUM_INPUT2_CC0_CC_PWM_CFG_cc_out_ccu_0_OFS)&TIMER_TIMG_NUM_INPUT2_CC0_CC_PWM_CFG_cc_out_ccu_0_MASK) + ((cc_out_load_0<<TIMER_TIMG_NUM_INPUT2_CC0_CC_PWM_CFG_cc_out_load_0_OFS)&TIMER_TIMG_NUM_INPUT2_CC0_CC_PWM_CFG_cc_out_load_0_MASK) + ((cc_out_zero_0<<TIMER_TIMG_NUM_INPUT2_CC0_CC_PWM_CFG_cc_out_zero_0_OFS)&TIMER_TIMG_NUM_INPUT2_CC0_CC_PWM_CFG_cc_out_zero_0_MASK);
}

static inline void TIMER_TIMG_NUM_INPUT2_CC1_CC_PWM_CFG_WRITE(TIMER_TIMG_NUM_INPUT2_REGS_s * registers, uint32_t cc_out_cc2d_1, uint32_t cc_out_cc2u_1, uint32_t cc_out_ccd_1, uint32_t cc_out_ccu_1, uint32_t cc_out_load_1, uint32_t cc_out_zero_1) {
    registers->CC1_CC_PWM_CFG.packed_w =  + ((cc_out_cc2d_1<<TIMER_TIMG_NUM_INPUT2_CC1_CC_PWM_CFG_cc_out_cc2d_1_OFS)&TIMER_TIMG_NUM_INPUT2_CC1_CC_PWM_CFG_cc_out_cc2d_1_MASK) + ((cc_out_cc2u_1<<TIMER_TIMG_NUM_INPUT2_CC1_CC_PWM_CFG_cc_out_cc2u_1_OFS)&TIMER_TIMG_NUM_INPUT2_CC1_CC_PWM_CFG_cc_out_cc2u_1_MASK) + ((cc_out_ccd_1<<TIMER_TIMG_NUM_INPUT2_CC1_CC_PWM_CFG_cc_out_ccd_1_OFS)&TIMER_TIMG_NUM_INPUT2_CC1_CC_PWM_CFG_cc_out_ccd_1_MASK) + ((cc_out_ccu_1<<TIMER_TIMG_NUM_INPUT2_CC1_CC_PWM_CFG_cc_out_ccu_1_OFS)&TIMER_TIMG_NUM_INPUT2_CC1_CC_PWM_CFG_cc_out_ccu_1_MASK) + ((cc_out_load_1<<TIMER_TIMG_NUM_INPUT2_CC1_CC_PWM_CFG_cc_out_load_1_OFS)&TIMER_TIMG_NUM_INPUT2_CC1_CC_PWM_CFG_cc_out_load_1_MASK) + ((cc_out_zero_1<<TIMER_TIMG_NUM_INPUT2_CC1_CC_PWM_CFG_cc_out_zero_1_OFS)&TIMER_TIMG_NUM_INPUT2_CC1_CC_PWM_CFG_cc_out_zero_1_MASK);
}

static inline void TIMER_TIMG_NUM_INPUT2_CC0_OUTPUT_CTL_WRITE(TIMER_TIMG_NUM_INPUT2_REGS_s * registers, uint32_t cc_out_sel_0, uint32_t cc_out_inv_0, uint32_t cc_out_val_init_0) {
    registers->CC0_OUTPUT_CTL.packed_w =  + ((cc_out_sel_0<<TIMER_TIMG_NUM_INPUT2_CC0_OUTPUT_CTL_cc_out_sel_0_OFS)&TIMER_TIMG_NUM_INPUT2_CC0_OUTPUT_CTL_cc_out_sel_0_MASK) + ((cc_out_inv_0<<TIMER_TIMG_NUM_INPUT2_CC0_OUTPUT_CTL_cc_out_inv_0_OFS)&TIMER_TIMG_NUM_INPUT2_CC0_OUTPUT_CTL_cc_out_inv_0_MASK) + ((cc_out_val_init_0<<TIMER_TIMG_NUM_INPUT2_CC0_OUTPUT_CTL_cc_out_val_init_0_OFS)&TIMER_TIMG_NUM_INPUT2_CC0_OUTPUT_CTL_cc_out_val_init_0_MASK);
}

static inline void TIMER_TIMG_NUM_INPUT2_CC1_OUTPUT_CTL_WRITE(TIMER_TIMG_NUM_INPUT2_REGS_s * registers, uint32_t cc_out_sel_1, uint32_t cc_out_inv_1, uint32_t cc_out_val_init_1) {
    registers->CC1_OUTPUT_CTL.packed_w =  + ((cc_out_sel_1<<TIMER_TIMG_NUM_INPUT2_CC1_OUTPUT_CTL_cc_out_sel_1_OFS)&TIMER_TIMG_NUM_INPUT2_CC1_OUTPUT_CTL_cc_out_sel_1_MASK) + ((cc_out_inv_1<<TIMER_TIMG_NUM_INPUT2_CC1_OUTPUT_CTL_cc_out_inv_1_OFS)&TIMER_TIMG_NUM_INPUT2_CC1_OUTPUT_CTL_cc_out_inv_1_MASK) + ((cc_out_val_init_1<<TIMER_TIMG_NUM_INPUT2_CC1_OUTPUT_CTL_cc_out_val_init_1_OFS)&TIMER_TIMG_NUM_INPUT2_CC1_OUTPUT_CTL_cc_out_val_init_1_MASK);
}

static inline void TIMER_TIMG_NUM_INPUT2_CC0_SW_FORCE_WRITE(TIMER_TIMG_NUM_INPUT2_REGS_s * registers, uint32_t cc_out_sw_force_0) {
    registers->CC0_SW_FORCE.packed_w =  + ((cc_out_sw_force_0<<TIMER_TIMG_NUM_INPUT2_CC0_SW_FORCE_cc_out_sw_force_0_OFS)&TIMER_TIMG_NUM_INPUT2_CC0_SW_FORCE_cc_out_sw_force_0_MASK);
}

static inline void TIMER_TIMG_NUM_INPUT2_CC1_SW_FORCE_WRITE(TIMER_TIMG_NUM_INPUT2_REGS_s * registers, uint32_t cc_out_sw_force_1) {
    registers->CC1_SW_FORCE.packed_w =  + ((cc_out_sw_force_1<<TIMER_TIMG_NUM_INPUT2_CC1_SW_FORCE_cc_out_sw_force_1_OFS)&TIMER_TIMG_NUM_INPUT2_CC1_SW_FORCE_cc_out_sw_force_1_MASK);
}

static inline void TIMER_TIMG_NUM_INPUT2_CTR_CTL_WRITE(TIMER_TIMG_NUM_INPUT2_REGS_s * registers, uint32_t ctr_en, uint32_t repeat_mode, uint32_t count_mode, uint32_t ctr_zero_ctrl, uint32_t ctr_load_ctrl, uint32_t ctr_adv_ctrl, uint32_t suppress_ctr_event_gen) {
    registers->CTR_CTL.packed_w =  + ((ctr_en<<TIMER_TIMG_NUM_INPUT2_CTR_CTL_ctr_en_OFS)&TIMER_TIMG_NUM_INPUT2_CTR_CTL_ctr_en_MASK) + ((repeat_mode<<TIMER_TIMG_NUM_INPUT2_CTR_CTL_repeat_mode_OFS)&TIMER_TIMG_NUM_INPUT2_CTR_CTL_repeat_mode_MASK) + ((count_mode<<TIMER_TIMG_NUM_INPUT2_CTR_CTL_count_mode_OFS)&TIMER_TIMG_NUM_INPUT2_CTR_CTL_count_mode_MASK) + ((ctr_zero_ctrl<<TIMER_TIMG_NUM_INPUT2_CTR_CTL_ctr_zero_ctrl_OFS)&TIMER_TIMG_NUM_INPUT2_CTR_CTL_ctr_zero_ctrl_MASK) + ((ctr_load_ctrl<<TIMER_TIMG_NUM_INPUT2_CTR_CTL_ctr_load_ctrl_OFS)&TIMER_TIMG_NUM_INPUT2_CTR_CTL_ctr_load_ctrl_MASK) + ((ctr_adv_ctrl<<TIMER_TIMG_NUM_INPUT2_CTR_CTL_ctr_adv_ctrl_OFS)&TIMER_TIMG_NUM_INPUT2_CTR_CTL_ctr_adv_ctrl_MASK) + ((suppress_ctr_event_gen<<TIMER_TIMG_NUM_INPUT2_CTR_CTL_suppress_ctr_event_gen_OFS)&TIMER_TIMG_NUM_INPUT2_CTR_CTL_suppress_ctr_event_gen_MASK);
}

static inline void TIMER_TIMG_NUM_INPUT2_CTR_VAL_WRITE(TIMER_TIMG_NUM_INPUT2_REGS_s * registers, uint32_t ctr_val) {
    registers->CTR_VAL.packed_w =  + ((ctr_val<<TIMER_TIMG_NUM_INPUT2_CTR_VAL_ctr_val_OFS)&TIMER_TIMG_NUM_INPUT2_CTR_VAL_ctr_val_MASK);
}

static inline void TIMER_TIMG_NUM_INPUT2_CTR_LOAD_VAL_WRITE(TIMER_TIMG_NUM_INPUT2_REGS_s * registers, uint32_t ctr_load_val) {
    registers->CTR_LOAD_VAL.packed_w =  + ((ctr_load_val<<TIMER_TIMG_NUM_INPUT2_CTR_LOAD_VAL_ctr_load_val_OFS)&TIMER_TIMG_NUM_INPUT2_CTR_LOAD_VAL_ctr_load_val_MASK);
}

static inline void TIMER_TIMG_NUM_INPUT2_DEBUG_CTRL_WRITE(TIMER_TIMG_NUM_INPUT2_REGS_s * registers, uint32_t run_in_halt_mode) {
    registers->DEBUG_CTRL.packed_w =  + ((run_in_halt_mode<<TIMER_TIMG_NUM_INPUT2_DEBUG_CTRL_run_in_halt_mode_OFS)&TIMER_TIMG_NUM_INPUT2_DEBUG_CTRL_run_in_halt_mode_MASK);
}

